CREATE INDEX ENUM_TBNAME ON Enumeration(TABLENAME) TABLESPACE INDEXES;
CREATE INDEX ENUM_COLNAME ON Enumeration(COLUMNNAME) TABLESPACE INDEXES;
CREATE INDEX ENUM_VALUE ON Enumeration(VALUE) TABLESPACE INDEXES;

CREATE INDEX DATASET_NAME_Version ON DataSet(Name,Version) TABLESPACE INDEXES;

CREATE INDEX DATASETHIERARCHY_SuperWID ON DataSetHierarchy(SuperWID) TABLESPACE INDEXES;
CREATE INDEX DATASETHIERARCHY_SubWID ON DataSetHierarchy(SubWID) TABLESPACE INDEXES;

CREATE INDEX ENTRY_INSERTDATE ON Entry(InsertDate) TABLESPACE INDEXES;
CREATE INDEX ENTRY_CREATEDATE ON Entry(CreationDate) TABLESPACE INDEXES;
CREATE INDEX ENTRY_MODDATE ON Entry(ModifiedDate) TABLESPACE INDEXES;
CREATE INDEX ENTRY_DATASETWID ON Entry(DatasetWID) TABLESPACE INDEXES;

CREATE INDEX ELEMENT_NAME ON Element(Name) TABLESPACE INDEXES;
CREATE INDEX ELEMENT_ELEMENTSYMBOL ON Element(ElementSymbol) TABLESPACE INDEXES;
CREATE INDEX ELEMENT_ATOMICWEIGHT ON Element(AtomicWeight) TABLESPACE INDEXES;
CREATE INDEX ELEMENT_ATOMICNUMBER ON Element(AtomicNumber) TABLESPACE INDEXES;

CREATE INDEX VALENCE_WID ON Valence(OtherWID) TABLESPACE INDEXES;
CREATE INDEX VALENCE_VALENCE ON Valence(Valence) TABLESPACE INDEXES;

CREATE INDEX LightSource_Instrument ON LightSource(InstrumentWID) TABLESPACE INDEXES;
CREATE INDEX LightSource_Wavelength ON LightSource(Wavelength) TABLESPACE INDEXES;

CREATE INDEX FlowCytometrySample_BioSource ON FlowCytometrySample(BioSourceWID) TABLESPACE INDEXES;
CREATE INDEX FlowCytometrySample_Manufac ON FlowCytometrySample(ManufacturerWID) TABLESPACE INDEXES;
CREATE INDEX FlowCytometrySample_Meas ON FlowCytometrySample(MeasurementWID) TABLESPACE INDEXES;
CREATE INDEX FlowCytometrySample_Probe ON FlowCytometrySample(FlowCytometryProbeWID) TABLESPACE INDEXES;


CREATE INDEX TranscriptionUnit_Name ON TranscriptionUnit(Name) TABLESPACE INDEXES;

CREATE INDEX TranscriptionUnitComponent_TU ON TranscriptionUnitComponent(TranscriptionUnitWID) TABLESPACE INDEXES;
CREATE INDEX TranscriptionUnitComponent_OW ON TranscriptionUnitComponent(OtherWID) TABLESPACE INDEXES;

CREATE INDEX CHEMICAL_BEILSTEINNAME ON Chemical(BEILSTEINNAME) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_SYSTEMATICNAME ON Chemical(SYSTEMATICNAME) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_CAS ON Chemical(CAS) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_CHARGE ON Chemical(CHARGE) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_EMPIRICALFORMULA ON Chemical(EMPIRICALFORMULA) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_MOLEWEIGHTCALC ON Chemical(MOLECULARWEIGHTCALC) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_MOLEWEIGHTEXP ON Chemical(MOLECULARWEIGHTEXP) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_OCTH2OCOEFF ON Chemical(OCTH2OPARTITIONCOEFF) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_PKA1 ON Chemical(PKA1) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_PKA2 ON Chemical(PKA2) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_PKA3 ON Chemical(PKA3) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_SMILES ON Chemical(SMILES) TABLESPACE INDEXES;
CREATE INDEX CHEMICAL_DATASETWID ON Chemical(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX REACTION_DeltaG ON Reaction(DeltaG) TABLESPACE INDEXES;
CREATE INDEX REACTION_ECNumber ON Reaction(ECNumber) TABLESPACE INDEXES;
CREATE INDEX REACTION_ECNumberProposed ON Reaction(ECNumberProposed) TABLESPACE INDEXES;


CREATE INDEX PROTEIN_NAME ON Protein(NAME) TABLESPACE INDEXES;
CREATE INDEX PROTEIN_CHARGE ON Protein(CHARGE) TABLESPACE INDEXES;
CREATE INDEX PROTEIN_MOLEWEIGHTCALC ON Protein(MOLECULARWEIGHTCALC) TABLESPACE INDEXES;
CREATE INDEX PROTEIN_MOLEWEIGHTEXP ON Protein(MOLECULARWEIGHTEXP) TABLESPACE INDEXES;
CREATE INDEX PROTEIN_PICALC ON Protein(PICALC) TABLESPACE INDEXES;
CREATE INDEX PROTEIN_PIEXP ON Protein(PIEXP) TABLESPACE INDEXES;

CREATE INDEX FEATURE_Description ON Feature(Description) TABLESPACE INDEXES;
CREATE INDEX FEATURE_TYPE ON Feature(Type) TABLESPACE INDEXES;
CREATE INDEX FEATURE_Class ON Feature(Class) TABLESPACE INDEXES;
CREATE INDEX FEATURE_SequenceWID ON Feature(SequenceWID) TABLESPACE INDEXES;
CREATE INDEX FEATURE_START_ENDPOS ON Feature(STARTPOSITION,ENDPOSITION) TABLESPACE INDEXES;
CREATE INDEX FEATURE_ENDPOSITION ON Feature(ENDPOSITION) TABLESPACE INDEXES;
CREATE INDEX FEATURE_DATASETWID ON Feature(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX FUNCTION_NAME ON Function(NAME) TABLESPACE INDEXES;
CREATE INDEX FUNCTION_DATASETWID ON Function(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX ER_REAWID ON EnzymaticReaction(REACTIONWID) TABLESPACE INDEXES;
CREATE INDEX ER_PROWID ON EnzymaticReaction(PROTEINWID) TABLESPACE INDEXES;
CREATE INDEX ER_COMWID ON EnzymaticReaction(COMPLEXWID) TABLESPACE INDEXES;
CREATE INDEX ER_DIRWID ON EnzymaticReaction(REACTIONDIRECTION) TABLESPACE INDEXES;

CREATE INDEX GENCODE_NAME ON GeneticCode(NAME) TABLESPACE INDEXES;
CREATE INDEX GENCODE_TRANSTABLE ON GeneticCode(TRANSLATIONTABLE) TABLESPACE INDEXES;
CREATE INDEX GENCODE_STARTCODON ON GeneticCode(STARTCODON) TABLESPACE INDEXES;
CREATE INDEX GENCODE_DATASETWID ON GeneticCode(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX DIVISION_NAME ON Division(NAME) TABLESPACE INDEXES;
CREATE INDEX DIVISION_DIVCODE ON Division(CODE) TABLESPACE INDEXES;
CREATE INDEX DIVISION_DATASETWID ON Division(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX TAXON_PARENTWID ON Taxon(PARENTWID) TABLESPACE INDEXES;
CREATE INDEX TAXON_NAME ON Taxon(NAME) TABLESPACE INDEXES;
CREATE INDEX TAXON_RANK ON Taxon(RANK) TABLESPACE INDEXES;
CREATE INDEX TAXON_DIVWID ON Taxon(DIVISIONWID) TABLESPACE INDEXES;
CREATE INDEX TAXON_GENCODEWID ON Taxon(GENCODEWID) TABLESPACE INDEXES;
CREATE INDEX TAXON_MCGENCODEWID ON Taxon(MCGENCODEWID) TABLESPACE INDEXES;
CREATE INDEX TAXON_DATASETWID ON Taxon(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX BIOSOURCE_NAME ON BioSource(Name) TABLESPACE INDEXES;
CREATE INDEX BIOSOURCE_STRAIN ON BioSource(Strain) TABLESPACE INDEXES;
CREATE INDEX BIOSOURCE_ATCC ON BioSource(ATCCId) TABLESPACE INDEXES;
CREATE INDEX BIOSOURCE_TAXONWID ON BioSource(TAXONWID) TABLESPACE INDEXES;
CREATE INDEX BIOSOURCE_DATASETWID ON BioSource(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX BIOSUBTYPE_Type ON BioSubtype(Type) TABLESPACE INDEXES;
CREATE INDEX BIOSUBTYPE_Value ON BioSubtype(Value) TABLESPACE INDEXES;
CREATE INDEX BIOSUBTYPE_DATASETWID ON BioSubtype(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX NUCLEICACID_Name ON NucleicAcid(Name) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_Type ON NucleicAcid(Type) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_Class ON NucleicAcid(Class) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_MoleculeLength ON NucleicAcid(MoleculeLength) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_CumulativeLength ON NucleicAcid(CumulativeLength) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_GCWID ON NucleicAcid(GeneticCodeWID) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_BSWID ON NucleicAcid(BioSourceWID) TABLESPACE INDEXES;
CREATE INDEX NUCLEICACID_DATASETWID ON NucleicAcid(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX Subsequence_NAWID ON Subsequence(NucleicAcidWID) TABLESPACE INDEXES;
CREATE INDEX Subsequence_Length ON Subsequence(Length) TABLESPACE INDEXES;
CREATE INDEX Subsequence_PercentGC ON Subsequence(PercentGC) TABLESPACE INDEXES;
CREATE INDEX Subsequence_DWID ON Subsequence(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX GENE_Name ON Gene(Name) TABLESPACE INDEXES;
CREATE INDEX GENE_Type ON Gene(Type) TABLESPACE INDEXES;
CREATE INDEX GENE_GenomeID ON Gene(GenomeID) TABLESPACE INDEXES;
CREATE INDEX GENE_START_END_POSITION ON Gene(CODINGREGIONSTART, CODINGREGIONEND) TABLESPACE INDEXES;
CREATE INDEX GENE_ENDPOSITION ON Gene(CODINGREGIONEND) TABLESPACE INDEXES;
CREATE INDEX GENE_NAWID ON Gene(NucleicAcidWID) TABLESPACE INDEXES;
CREATE INDEX GENE_SubsequenceWID ON Gene(SubsequenceWID) TABLESPACE INDEXES;

CREATE INDEX PATHWAY_Name ON Pathway(Name) TABLESPACE INDEXES;

CREATE INDEX TERM_NAME ON Term(NAME) TABLESPACE INDEXES;

CREATE INDEX COMPUTATION_NAME ON Computation(NAME) TABLESPACE INDEXES;
CREATE INDEX COMPUTATION_DATASETWID ON Computation(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX CITATION_DATASETWID ON Citation(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX ARCHIVE_OTHERWID ON Archive(OTHERWID) TABLESPACE INDEXES;
CREATE INDEX ARCHIVE_TOOL ON Archive(TOOLNAME) TABLESPACE INDEXES;
CREATE INDEX ARCHIVE_DATASETWID ON Archive(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX EXP_TYPE ON Experiment(TYPE) TABLESPACE INDEXES;
CREATE INDEX EXP_CON ON Experiment(CONTACTWID) TABLESPACE INDEXES;
CREATE INDEX EXP_GROUP ON Experiment(GROUPWID) TABLESPACE INDEXES;
CREATE INDEX EXP_DS ON Experiment(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX EXPDATA_ExperimentWID ON ExperimentData(ExperimentWID) TABLESPACE INDEXES;
CREATE INDEX EXPDATA_Kind ON ExperimentData(Kind) TABLESPACE INDEXES;
CREATE INDEX EXPDATA_MageData ON ExperimentData(MageData) TABLESPACE INDEXES;
CREATE INDEX EXPDATA_OtherWID ON ExperimentData(OtherWID) TABLESPACE INDEXES;
CREATE INDEX EXPDATA_DS ON ExperimentData(DATASETWID) TABLESPACE INDEXES;

CREATE INDEX SUPPORT_OTHERWID ON Support(OTHERWID) TABLESPACE INDEXES;
CREATE INDEX SUPPORT_TYPE ON Support(TYPE) TABLESPACE INDEXES;
CREATE INDEX SUPPORT_CONFIDENCE ON Support(CONFIDENCE) TABLESPACE INDEXES;

CREATE INDEX CA_WID ON ChemicalAtom(CHEMICALWID) TABLESPACE INDEXES;
CREATE INDEX CA_ATOMINDEX ON ChemicalAtom(ATOMINDEX) TABLESPACE INDEXES;
CREATE INDEX CA_ATOM ON ChemicalAtom(ATOM) TABLESPACE INDEXES;
CREATE INDEX CA_CHARGE ON ChemicalAtom(CHARGE) TABLESPACE INDEXES;
CREATE INDEX CA_X ON ChemicalAtom(X) TABLESPACE INDEXES;
CREATE INDEX CA_Y ON ChemicalAtom(Y) TABLESPACE INDEXES;
CREATE INDEX CA_Z ON ChemicalAtom(Z) TABLESPACE INDEXES;
CREATE INDEX CA_SPARITY ON ChemicalAtom(STEREOPARITY) TABLESPACE INDEXES;

CREATE INDEX CB_WID ON ChemicalBond(ChemicalWID) TABLESPACE INDEXES;
CREATE INDEX CB_INDEX1 ON ChemicalBond(ATOM1INDEX) TABLESPACE INDEXES;
CREATE INDEX CB_INDEX2 ON ChemicalBond(ATOM2INDEX) TABLESPACE INDEXES;
CREATE INDEX CB_BONDTYPE ON ChemicalBond(BONDTYPE) TABLESPACE INDEXES;
CREATE INDEX CB_BONDSTEREO ON ChemicalBond(BONDSTEREO) TABLESPACE INDEXES;

CREATE INDEX ERCOFACTOR_ERWID ON EnzReactionCofactor(ENZYMATICREACTIONWID) TABLESPACE INDEXES;
CREATE INDEX ERCOFACTOR_CHEMWID ON EnzReactionCofactor(CHEMICALWID) TABLESPACE INDEXES;

CREATE INDEX ERALT_ERWID ON EnzReactionAltCompound(ENZYMATICREACTIONWID) TABLESPACE INDEXES;
CREATE INDEX ERALT_PRIMWID ON EnzReactionAltCompound(PRIMARYWID) TABLESPACE INDEXES;
CREATE INDEX ERALT_ALTWID ON EnzReactionAltCompound(ALTERNATIVEWID) TABLESPACE INDEXES;

CREATE INDEX ERIA_ERWID ON EnzReactionInhibitorActivator(ENZYMATICREACTIONWID) TABLESPACE INDEXES;
CREATE INDEX ERIA_COMPOUNDWID ON EnzReactionInhibitorActivator(CompoundWID) TABLESPACE INDEXES;
CREATE INDEX ERIA_MECH ON EnzReactionInhibitorActivator(Mechanism) TABLESPACE INDEXES;

CREATE INDEX LOCATION_ProteinWID ON Location(ProteinWID) TABLESPACE INDEXES;

CREATE INDEX PATHLINK_P1WID_P2WID_CHEMWID ON PathwayLink(PATHWAY1WID, PATHWAY2WID, CHEMICALWID) TABLESPACE INDEXES;
CREATE INDEX PATHLINK_P2WID ON PathwayLink(PATHWAY2WID) TABLESPACE INDEXES;
CREATE INDEX PATHLINK_CHEMWID ON PathwayLink(CHEMICALWID) TABLESPACE INDEXES;

CREATE INDEX PR_REACTIONWID ON PathwayReaction(ReactionWID) TABLESPACE INDEXES;
CREATE INDEX PR_PRIORWID ON PathwayReaction(PriorReactionWID) TABLESPACE INDEXES;

CREATE INDEX PRODUCT_REACTWID ON Product(REACTIONWID) TABLESPACE INDEXES;
CREATE INDEX PRODUCT_OTHERWID ON Product(OTHERWID) TABLESPACE INDEXES;
CREATE INDEX PRODUCT_COEFFICIENT ON Product(COEFFICIENT) TABLESPACE INDEXES;

CREATE INDEX REACTANT_WID ON Reactant(ReactionWID) TABLESPACE INDEXES;
CREATE INDEX REACTANT_OTHERWID ON Reactant(OTHERWID) TABLESPACE INDEXES;
CREATE INDEX REACTANT_COEFFICIENT ON Reactant(Coefficient) TABLESPACE INDEXES;


CREATE INDEX SM_QUERYWID ON SequenceMatch(QueryWID) TABLESPACE INDEXES;
CREATE INDEX SM_MATCHWID ON SequenceMatch(MatchWID) TABLESPACE INDEXES;
CREATE INDEX SM_COMPUTATIONWID ON SequenceMatch(ComputationWID) TABLESPACE INDEXES;
CREATE INDEX SM_EVALUE ON SequenceMatch(EValue) TABLESPACE INDEXES;
CREATE INDEX SM_PVALUE ON SequenceMatch(PValue) TABLESPACE INDEXES;
CREATE INDEX SM_PIDENTICAL ON SequenceMatch(PercentIdentical) TABLESPACE INDEXES;
CREATE INDEX SM_PSIMILAR ON SequenceMatch(PercentSimilar) TABLESPACE INDEXES;
CREATE INDEX SM_RANK ON SequenceMatch(Rank) TABLESPACE INDEXES;
CREATE INDEX SM_LENGTH ON SequenceMatch(Length) TABLESPACE INDEXES;
CREATE INDEX SM_QSTART_QEND ON SequenceMatch(QueryStart, QueryEnd) TABLESPACE INDEXES;
CREATE INDEX SM_QEND ON SequenceMatch(QueryEnd) TABLESPACE INDEXES;
CREATE INDEX SM_MSTART_MEND ON SequenceMatch(MatchStart,MatchEnd) TABLESPACE INDEXES;
CREATE INDEX SM_MEND ON SequenceMatch(MatchEnd) TABLESPACE INDEXES;

CREATE INDEX SUBUNIT_PROW1ID ON Subunit(COMPLEXWID) TABLESPACE INDEXES;
CREATE INDEX SUBUNIT_PROW2ID ON Subunit(SubunitWID) TABLESPACE INDEXES;
CREATE INDEX SUBUNIT_COEF ON Subunit(COEFFICIENT) TABLESPACE INDEXES;

CREATE INDEX SUPER_SUBWID_SUPERWID ON SuperPathway(SUBPATHWAYWID,SUPERPATHWAYWID) TABLESPACE INDEXES;
CREATE INDEX SUPER_SUPERWID_SUBWID ON SuperPathway(SUPERPATHWAYWID,SUBPATHWAYWID) TABLESPACE INDEXES;

CREATE INDEX TR_TermRelationship ON TermRelationship(TermWID,RelatedTermWID) TABLESPACE INDEXES;
CREATE INDEX RT_TermRelationship ON TermRelationship(RelatedTermWID,TermWID) TABLESPACE INDEXES;

CREATE INDEX TO_RelatedTerm ON RelatedTerm(TermWID,OtherWID) TABLESPACE INDEXES;
CREATE INDEX OT_RelatedTerm ON RelatedTerm(OtherWID,TermWID) TABLESPACE INDEXES;

CREATE INDEX CO_OTHERWID_CITATIONWID ON CitationWIDOtherWID(OtherWID,CitationWID) TABLESPACE INDEXES;
CREATE INDEX CO_CITATIONWID_OTHERWID ON CitationWIDOtherWID(CitationWID,OtherWID) TABLESPACE INDEXES;

CREATE INDEX COMMENT_OTHERWID ON CommentTable( OTHERWID ) TABLESPACE INDEXES;

CREATE INDEX CROSS_OTHERWID ON CrossReference(OTHERWID) TABLESPACE INDEXES;
CREATE INDEX CROSS_XID ON CrossReference(XID) TABLESPACE INDEXES;

CREATE INDEX Description_OTHERWID ON Description( OTHERWID ) TABLESPACE INDEXES;


CREATE INDEX SYNONYM_SYN ON SynonymTable(Syn) TABLESPACE INDEXES;

CREATE INDEX TOOL_OTHERWID ON ToolAdvice(OtherWID) TABLESPACE INDEXES;
CREATE INDEX TOOL_NAME ON ToolAdvice(ToolName) TABLESPACE INDEXES;

CREATE INDEX BB_BSWID_BSTWID ON BioSourceWIDBioSubtypeWID(BioSourceWID, BioSubtypeWID) TABLESPACE INDEXES;
CREATE INDEX BB_BSTWID_BSWID ON BioSourceWIDBioSubtypeWID(BioSubtypeWID, BioSourceWID) TABLESPACE INDEXES;

CREATE INDEX BG_BIOSOURCEWID_GENEWID ON BioSourceWIDGeneWID(BioSourceWID, GENEWID) TABLESPACE INDEXES;
CREATE INDEX BG_GENEWID_BIOSOURCEWID ON BioSourceWIDGeneWID(GENEWID, BioSourceWID) TABLESPACE INDEXES;

CREATE INDEX BP_BIOSOURCEWID_PROWID ON BioSourceWIDProteinWID(BioSourceWID,PROTEINWID) TABLESPACE INDEXES;
CREATE INDEX BP_PROWID_BIOSOURCEWID ON BioSourceWIDProteinWID(PROTEINWID, BioSourceWID) TABLESPACE INDEXES;

CREATE INDEX GN_GENEWID_NAWID ON GeneWIDNucleicAcidWID(GENEWID,NUCLEICACIDWID) TABLESPACE INDEXES;
CREATE INDEX GN_NAWID_GENEWID ON GeneWIDNucleicAcidWID(NUCLEICACIDWID,GENEWID) TABLESPACE INDEXES;

CREATE INDEX GP_GENEWID_PROWID ON GeneWIDProteinWID(GENEWID,PROTEINWID) TABLESPACE INDEXES;
CREATE INDEX GP_PROWID_GENEWID ON GeneWIDProteinWID(PROTEINWID,GENEWID) TABLESPACE INDEXES;

CREATE INDEX PF_FunctionWID_PROWID ON ProteinWIDFunctionWID(FunctionWID,PROTEINWID) TABLESPACE INDEXES;
CREATE INDEX PF_PROWID_FunctionWID ON ProteinWIDFunctionWID(PROTEINWID,FunctionWID) TABLESPACE INDEXES;

CREATE INDEX PS_PROTEINWID_SPOTWID ON ProteinWIDSpotWID(ProteinWID, SpotWID) TABLESPACE INDEXES;
CREATE INDEX PS_SPOTWID_PROTEINWID ON ProteinWIDSpotWID(SpotWID, ProteinWID) TABLESPACE INDEXES;

CREATE INDEX SM_SPOTWID_IDMETHWID ON SpotWIDSpotIdMethodWID(SpotWID, SpotIdMethodWID) TABLESPACE INDEXES;
CREATE INDEX SM_IDMETHWID_SPOTWID ON SpotWIDSpotIdMethodWID(SpotIdMethodWID, SpotWID) TABLESPACE INDEXES;

CREATE INDEX NameValueType1 ON NameValueType(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX NameValueType2 ON NameValueType(Name) TABLESPACE INDEXES;
CREATE INDEX NameValueType3 ON NameValueType(Value) TABLESPACE INDEXES;
CREATE INDEX NameValueType4 ON NameValueType(Type_) TABLESPACE INDEXES;
CREATE INDEX NameValueType5 ON NameValueType(NameValueType_PropertySets) TABLESPACE INDEXES;
CREATE INDEX NameValueType6 ON NameValueType(OtherWID) TABLESPACE INDEXES;

CREATE INDEX Contact1 ON Contact(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Contact2 ON Contact(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX Contact3 ON Contact(Identifier) TABLESPACE INDEXES;
CREATE INDEX Contact4 ON Contact(Name) TABLESPACE INDEXES;
CREATE INDEX Contact5 ON Contact(URI) TABLESPACE INDEXES;
CREATE INDEX Contact6 ON Contact(Address) TABLESPACE INDEXES;
CREATE INDEX Contact7 ON Contact(Phone) TABLESPACE INDEXES;
CREATE INDEX Contact8 ON Contact(TollFreePhone) TABLESPACE INDEXES;
CREATE INDEX Contact9 ON Contact(Email) TABLESPACE INDEXES;
CREATE INDEX Contact10 ON Contact(Fax) TABLESPACE INDEXES;
CREATE INDEX Contact11 ON Contact(Parent) TABLESPACE INDEXES;
CREATE INDEX Contact12 ON Contact(LastName) TABLESPACE INDEXES;
CREATE INDEX Contact13 ON Contact(FirstName) TABLESPACE INDEXES;
CREATE INDEX Contact14 ON Contact(MidInitials) TABLESPACE INDEXES;
CREATE INDEX Contact15 ON Contact(Affiliation) TABLESPACE INDEXES;

CREATE INDEX ArrayDesign1 ON ArrayDesign(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign2 ON ArrayDesign(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign3 ON ArrayDesign(Identifier) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign4 ON ArrayDesign(Name) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign5 ON ArrayDesign(Version) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign6 ON ArrayDesign(NumberOfFeatures) TABLESPACE INDEXES;
CREATE INDEX ArrayDesign7 ON ArrayDesign(SurfaceType) TABLESPACE INDEXES;

CREATE INDEX DesignElementGroup1 ON DesignElementGroup(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup2 ON DesignElementGroup(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup3 ON DesignElementGroup(Identifier) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup4 ON DesignElementGroup(Name) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup5 ON DesignElementGroup(ArrayDesign_FeatureGroups) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup6 ON DesignElementGroup(DesignElementGroup_Species) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup7 ON DesignElementGroup(FeatureWidth) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup8 ON DesignElementGroup(FeatureLength) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup9 ON DesignElementGroup(FeatureHeight) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup10 ON DesignElementGroup(FeatureGroup_TechnologyType) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup11 ON DesignElementGroup(FeatureGroup_FeatureShape) TABLESPACE INDEXES;
CREATE INDEX DesignElementGroup12 ON DesignElementGroup(FeatureGroup_DistanceUnit) TABLESPACE INDEXES;

CREATE INDEX Zone1 ON Zone(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Zone2 ON Zone(Identifier) TABLESPACE INDEXES;
CREATE INDEX Zone3 ON Zone(Name) TABLESPACE INDEXES;
CREATE INDEX Zone4 ON Zone(Row_) TABLESPACE INDEXES;
CREATE INDEX Zone5 ON Zone(Column_) TABLESPACE INDEXES;
CREATE INDEX Zone6 ON Zone(UpperLeftX) TABLESPACE INDEXES;
CREATE INDEX Zone7 ON Zone(UpperLeftY) TABLESPACE INDEXES;
CREATE INDEX Zone8 ON Zone(LowerRightX) TABLESPACE INDEXES;
CREATE INDEX Zone9 ON Zone(LowerRightY) TABLESPACE INDEXES;
CREATE INDEX Zone10 ON Zone(Zone_DistanceUnit) TABLESPACE INDEXES;
CREATE INDEX Zone11 ON Zone(ZoneGroup_ZoneLocations) TABLESPACE INDEXES;

CREATE INDEX ZoneGroup1 ON ZoneGroup(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup2 ON ZoneGroup(PhysicalArrayDesign_ZoneGroups) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup3 ON ZoneGroup(SpacingsBetweenZonesX) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup4 ON ZoneGroup(SpacingsBetweenZonesY) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup5 ON ZoneGroup(ZonesPerX) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup6 ON ZoneGroup(ZonesPerY) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup7 ON ZoneGroup(ZoneGroup_DistanceUnit) TABLESPACE INDEXES;
CREATE INDEX ZoneGroup8 ON ZoneGroup(ZoneGroup_ZoneLayout) TABLESPACE INDEXES;

CREATE INDEX ZoneLayout1 ON ZoneLayout(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ZoneLayout2 ON ZoneLayout(NumFeaturesPerRow) TABLESPACE INDEXES;
CREATE INDEX ZoneLayout3 ON ZoneLayout(NumFeaturesPerCol) TABLESPACE INDEXES;
CREATE INDEX ZoneLayout4 ON ZoneLayout(SpacingBetweenRows) TABLESPACE INDEXES;
CREATE INDEX ZoneLayout5 ON ZoneLayout(SpacingBetweenCols) TABLESPACE INDEXES;
CREATE INDEX ZoneLayout6 ON ZoneLayout(ZoneLayout_DistanceUnit) TABLESPACE INDEXES;

CREATE INDEX ExperimentDesign1 ON ExperimentDesign(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentDesign2 ON ExperimentDesign(Experiment_ExperimentDesigns) TABLESPACE INDEXES;
CREATE INDEX ExperimentDesign3 ON ExperimentDesign(QualityControlDescription) TABLESPACE INDEXES;
CREATE INDEX ExperimentDesign4 ON ExperimentDesign(NormalizationDescription) TABLESPACE INDEXES;
CREATE INDEX ExperimentDesign5 ON ExperimentDesign(ReplicateDescription) TABLESPACE INDEXES;

CREATE INDEX ExperimentalFactor1 ON ExperimentalFactor(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentalFactor2 ON ExperimentalFactor(Identifier) TABLESPACE INDEXES;
CREATE INDEX ExperimentalFactor3 ON ExperimentalFactor(Name) TABLESPACE INDEXES;
CREATE INDEX ExperimentalFactor4 ON ExperimentalFactor(ExperimentDesign) TABLESPACE INDEXES;
CREATE INDEX ExperimentalFactor5 ON ExperimentalFactor(ExperimentalFactor_Category) TABLESPACE INDEXES;

CREATE INDEX FactorValue1 ON FactorValue(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX FactorValue2 ON FactorValue(Identifier) TABLESPACE INDEXES;
CREATE INDEX FactorValue3 ON FactorValue(Name) TABLESPACE INDEXES;
CREATE INDEX FactorValue4 ON FactorValue(ExperimentalFactor) TABLESPACE INDEXES;
CREATE INDEX FactorValue5 ON FactorValue(ExperimentalFactor2) TABLESPACE INDEXES;
CREATE INDEX FactorValue6 ON FactorValue(FactorValue_Measurement) TABLESPACE INDEXES;
CREATE INDEX FactorValue7 ON FactorValue(FactorValue_Value) TABLESPACE INDEXES;

CREATE INDEX QuantitationType1 ON QuantitationType(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX QuantitationType2 ON QuantitationType(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX QuantitationType3 ON QuantitationType(Identifier) TABLESPACE INDEXES;
CREATE INDEX QuantitationType4 ON QuantitationType(Name) TABLESPACE INDEXES;
CREATE INDEX QuantitationType5 ON QuantitationType(IsBackground) TABLESPACE INDEXES;
CREATE INDEX QuantitationType6 ON QuantitationType(Channel) TABLESPACE INDEXES;
CREATE INDEX QuantitationType7 ON QuantitationType(QuantitationType_Scale) TABLESPACE INDEXES;
CREATE INDEX QuantitationType8 ON QuantitationType(QuantitationType_DataType) TABLESPACE INDEXES;
CREATE INDEX QuantitationType9 ON QuantitationType(TargetQuantitationType) TABLESPACE INDEXES;

CREATE INDEX Database_1 ON Database_(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Database_2 ON Database_(Identifier) TABLESPACE INDEXES;
CREATE INDEX Database_3 ON Database_(Name) TABLESPACE INDEXES;
CREATE INDEX Database_4 ON Database_(Version) TABLESPACE INDEXES;
CREATE INDEX Database_5 ON Database_(URI) TABLESPACE INDEXES;

CREATE INDEX Array_1 ON Array_(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Array_2 ON Array_(Identifier) TABLESPACE INDEXES;
CREATE INDEX Array_3 ON Array_(Name) TABLESPACE INDEXES;
CREATE INDEX Array_4 ON Array_(ArrayIdentifier) TABLESPACE INDEXES;
CREATE INDEX Array_5 ON Array_(ArrayXOrigin) TABLESPACE INDEXES;
CREATE INDEX Array_6 ON Array_(ArrayYOrigin) TABLESPACE INDEXES;
CREATE INDEX Array_7 ON Array_(OriginRelativeTo) TABLESPACE INDEXES;
CREATE INDEX Array_8 ON Array_(ArrayDesign) TABLESPACE INDEXES;
CREATE INDEX Array_9 ON Array_(Information) TABLESPACE INDEXES;
CREATE INDEX Array_10 ON Array_(ArrayGroup) TABLESPACE INDEXES;

CREATE INDEX ArrayGroup1 ON ArrayGroup(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup2 ON ArrayGroup(Identifier) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup3 ON ArrayGroup(Name) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup4 ON ArrayGroup(Barcode) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup5 ON ArrayGroup(ArraySpacingX) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup6 ON ArrayGroup(ArraySpacingY) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup7 ON ArrayGroup(NumArrays) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup8 ON ArrayGroup(OrientationMark) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup9 ON ArrayGroup(OrientationMarkPosition) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup10 ON ArrayGroup(Width) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup11 ON ArrayGroup(Length) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup12 ON ArrayGroup(ArrayGroup_SubstrateType) TABLESPACE INDEXES;
CREATE INDEX ArrayGroup13 ON ArrayGroup(ArrayGroup_DistanceUnit) TABLESPACE INDEXES;

CREATE INDEX ArrayManufacture1 ON ArrayManufacture(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ArrayManufacture2 ON ArrayManufacture(Identifier) TABLESPACE INDEXES;
CREATE INDEX ArrayManufacture3 ON ArrayManufacture(Name) TABLESPACE INDEXES;
CREATE INDEX ArrayManufacture4 ON ArrayManufacture(ManufacturingDate) TABLESPACE INDEXES;
CREATE INDEX ArrayManufacture5 ON ArrayManufacture(Tolerance) TABLESPACE INDEXES;

CREATE INDEX ArrayManufactureDeviation1 ON ArrayManufactureDeviation(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ArrayManufactureDeviation2 ON ArrayManufactureDeviation(Array_) TABLESPACE INDEXES;

CREATE INDEX FeatureDefect1 ON FeatureDefect(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX FeatureDefect2 ON FeatureDefect(ArrayManufactureDeviation) TABLESPACE INDEXES;
CREATE INDEX FeatureDefect3 ON FeatureDefect(FeatureDefect_DefectType) TABLESPACE INDEXES;
CREATE INDEX FeatureDefect4 ON FeatureDefect(FeatureDefect_PositionDelta) TABLESPACE INDEXES;
CREATE INDEX FeatureDefect5 ON FeatureDefect(Feature) TABLESPACE INDEXES;

CREATE INDEX Fiducial1 ON Fiducial(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Fiducial2 ON Fiducial(ArrayGroup_Fiducials) TABLESPACE INDEXES;
CREATE INDEX Fiducial3 ON Fiducial(Fiducial_FiducialType) TABLESPACE INDEXES;
CREATE INDEX Fiducial4 ON Fiducial(Fiducial_DistanceUnit) TABLESPACE INDEXES;
CREATE INDEX Fiducial5 ON Fiducial(Fiducial_Position) TABLESPACE INDEXES;

CREATE INDEX ManufactureLIMS1 ON ManufactureLIMS(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS2 ON ManufactureLIMS(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS3 ON ManufactureLIMS(ArrayManufacture_FeatureLIMSs) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS4 ON ManufactureLIMS(Quality) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS5 ON ManufactureLIMS(Feature) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS6 ON ManufactureLIMS(BioMaterial) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS7 ON ManufactureLIMS(ManufactureLIMS_IdentifierLIMS) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS8 ON ManufactureLIMS(BioMaterialPlateIdentifier) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS9 ON ManufactureLIMS(BioMaterialPlateRow) TABLESPACE INDEXES;
CREATE INDEX ManufactureLIMS10 ON ManufactureLIMS(BioMaterialPlateCol) TABLESPACE INDEXES;

CREATE INDEX PositionDelta1 ON PositionDelta(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX PositionDelta2 ON PositionDelta(DeltaX) TABLESPACE INDEXES;
CREATE INDEX PositionDelta3 ON PositionDelta(DeltaY) TABLESPACE INDEXES;
CREATE INDEX PositionDelta4 ON PositionDelta(PositionDelta_DistanceUnit) TABLESPACE INDEXES;

CREATE INDEX ZoneDefect1 ON ZoneDefect(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ZoneDefect2 ON ZoneDefect(ArrayManufactureDeviation) TABLESPACE INDEXES;
CREATE INDEX ZoneDefect3 ON ZoneDefect(ZoneDefect_DefectType) TABLESPACE INDEXES;
CREATE INDEX ZoneDefect4 ON ZoneDefect(ZoneDefect_PositionDelta) TABLESPACE INDEXES;
CREATE INDEX ZoneDefect5 ON ZoneDefect(Zone) TABLESPACE INDEXES;

CREATE INDEX SeqFeatureLocation1 ON SeqFeatureLocation(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX SeqFeatureLocation2 ON SeqFeatureLocation(SeqFeature_Regions) TABLESPACE INDEXES;
CREATE INDEX SeqFeatureLocation3 ON SeqFeatureLocation(StrandType) TABLESPACE INDEXES;
CREATE INDEX SeqFeatureLocation4 ON SeqFeatureLocation(SeqFeatureLocation_Subregions) TABLESPACE INDEXES;
CREATE INDEX SeqFeatureLocation5 ON SeqFeatureLocation(SeqFeatureLocation_Coordinate) TABLESPACE INDEXES;

CREATE INDEX SequencePosition1 ON SequencePosition(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX SequencePosition2 ON SequencePosition(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX SequencePosition3 ON SequencePosition(Start_) TABLESPACE INDEXES;
CREATE INDEX SequencePosition4 ON SequencePosition(End) TABLESPACE INDEXES;
CREATE INDEX SequencePosition5 ON SequencePosition(CompositeCompositeMap) TABLESPACE INDEXES;
CREATE INDEX SequencePosition6 ON SequencePosition(Composite) TABLESPACE INDEXES;
CREATE INDEX SequencePosition7 ON SequencePosition(ReporterCompositeMap) TABLESPACE INDEXES;
CREATE INDEX SequencePosition8 ON SequencePosition(Reporter) TABLESPACE INDEXES;

CREATE INDEX DesignElement1 ON DesignElement(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX DesignElement2 ON DesignElement(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX DesignElement3 ON DesignElement(Identifier) TABLESPACE INDEXES;
CREATE INDEX DesignElement4 ON DesignElement(Name) TABLESPACE INDEXES;
CREATE INDEX DesignElement5 ON DesignElement(FeatureGroup_Features) TABLESPACE INDEXES;
CREATE INDEX DesignElement6 ON DesignElement(DesignElement_ControlType) TABLESPACE INDEXES;
CREATE INDEX DesignElement7 ON DesignElement(Feature_Position) TABLESPACE INDEXES;
CREATE INDEX DesignElement8 ON DesignElement(Zone) TABLESPACE INDEXES;
CREATE INDEX DesignElement9 ON DesignElement(Feature_FeatureLocation) TABLESPACE INDEXES;
CREATE INDEX DesignElement10 ON DesignElement(FeatureGroup) TABLESPACE INDEXES;
CREATE INDEX DesignElement11 ON DesignElement(Reporter_WarningType) TABLESPACE INDEXES;

CREATE INDEX FeatureInformation1 ON FeatureInformation(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX FeatureInformation2 ON FeatureInformation(Feature) TABLESPACE INDEXES;
CREATE INDEX FeatureInformation3 ON FeatureInformation(FeatureReporterMap) TABLESPACE INDEXES;

CREATE INDEX FeatureLocation1 ON FeatureLocation(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX FeatureLocation2 ON FeatureLocation(Row_) TABLESPACE INDEXES;
CREATE INDEX FeatureLocation3 ON FeatureLocation(Column_) TABLESPACE INDEXES;

CREATE INDEX MismatchInformation1 ON MismatchInformation(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation2 ON MismatchInformation(CompositePosition) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation3 ON MismatchInformation(FeatureInformation) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation4 ON MismatchInformation(StartCoord) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation5 ON MismatchInformation(NewSequence) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation6 ON MismatchInformation(ReplacedLength) TABLESPACE INDEXES;
CREATE INDEX MismatchInformation7 ON MismatchInformation(ReporterPosition) TABLESPACE INDEXES;

CREATE INDEX Position_1 ON Position_(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Position_2 ON Position_(X) TABLESPACE INDEXES;
CREATE INDEX Position_3 ON Position_(Y) TABLESPACE INDEXES;
CREATE INDEX Position_4 ON Position_(Position_DistanceUnit) TABLESPACE INDEXES;

CREATE INDEX BioEvent1 ON BioEvent(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioEvent2 ON BioEvent(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX BioEvent3 ON BioEvent(Identifier) TABLESPACE INDEXES;
CREATE INDEX BioEvent4 ON BioEvent(Name) TABLESPACE INDEXES;
CREATE INDEX BioEvent5 ON BioEvent(CompositeSequence) TABLESPACE INDEXES;
CREATE INDEX BioEvent6 ON BioEvent(Reporter) TABLESPACE INDEXES;
CREATE INDEX BioEvent7 ON BioEvent(CompositeSequence2) TABLESPACE INDEXES;
CREATE INDEX BioEvent8 ON BioEvent(BioAssayMapTarget) TABLESPACE INDEXES;
CREATE INDEX BioEvent9 ON BioEvent(TargetQuantitationType) TABLESPACE INDEXES;
CREATE INDEX BioEvent10 ON BioEvent(DerivedBioAssayDataTarget) TABLESPACE INDEXES;
CREATE INDEX BioEvent11 ON BioEvent(QuantitationTypeMapping) TABLESPACE INDEXES;
CREATE INDEX BioEvent12 ON BioEvent(DesignElementMapping) TABLESPACE INDEXES;
CREATE INDEX BioEvent13 ON BioEvent(Transformation_BioAssayMapping) TABLESPACE INDEXES;
CREATE INDEX BioEvent14 ON BioEvent(BioMaterial_Treatments) TABLESPACE INDEXES;
CREATE INDEX BioEvent15 ON BioEvent(Order_) TABLESPACE INDEXES;
CREATE INDEX BioEvent16 ON BioEvent(Treatment_Action) TABLESPACE INDEXES;
CREATE INDEX BioEvent17 ON BioEvent(Treatment_ActionMeasurement) TABLESPACE INDEXES;
CREATE INDEX BioEvent18 ON BioEvent(Array_) TABLESPACE INDEXES;
CREATE INDEX BioEvent19 ON BioEvent(PhysicalBioAssayTarget) TABLESPACE INDEXES;
CREATE INDEX BioEvent20 ON BioEvent(PhysicalBioAssay) TABLESPACE INDEXES;
CREATE INDEX BioEvent21 ON BioEvent(Target) TABLESPACE INDEXES;
CREATE INDEX BioEvent22 ON BioEvent(PhysicalBioAssaySource) TABLESPACE INDEXES;
CREATE INDEX BioEvent23 ON BioEvent(MeasuredBioAssayTarget) TABLESPACE INDEXES;
CREATE INDEX BioEvent24 ON BioEvent(PhysicalBioAssay2) TABLESPACE INDEXES;

CREATE INDEX BioAssayData1 ON BioAssayData(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayData2 ON BioAssayData(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX BioAssayData3 ON BioAssayData(Identifier) TABLESPACE INDEXES;
CREATE INDEX BioAssayData4 ON BioAssayData(Name) TABLESPACE INDEXES;
CREATE INDEX BioAssayData5 ON BioAssayData(BioAssayDimension) TABLESPACE INDEXES;
CREATE INDEX BioAssayData6 ON BioAssayData(DesignElementDimension) TABLESPACE INDEXES;
CREATE INDEX BioAssayData7 ON BioAssayData(QuantitationTypeDimension) TABLESPACE INDEXES;
CREATE INDEX BioAssayData8 ON BioAssayData(BioAssayData_BioDataValues) TABLESPACE INDEXES;
CREATE INDEX BioAssayData9 ON BioAssayData(ProducerTransformation) TABLESPACE INDEXES;

CREATE INDEX BioAssayDimension1 ON BioAssayDimension(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayDimension2 ON BioAssayDimension(Identifier) TABLESPACE INDEXES;
CREATE INDEX BioAssayDimension3 ON BioAssayDimension(Name) TABLESPACE INDEXES;

CREATE INDEX BioAssayMapping1 ON BioAssayMapping(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX BioAssayTuple1 ON BioAssayTuple(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayTuple2 ON BioAssayTuple(BioAssay) TABLESPACE INDEXES;
CREATE INDEX BioAssayTuple3 ON BioAssayTuple(BioDataTuples_BioAssayTuples) TABLESPACE INDEXES;

CREATE INDEX BioDataValues1 ON BioDataValues(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioDataValues2 ON BioDataValues(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX BioDataValues3 ON BioDataValues(Order_) TABLESPACE INDEXES;
CREATE INDEX BioDataValues4 ON BioDataValues(BioDataCube_DataInternal) TABLESPACE INDEXES;
CREATE INDEX BioDataValues5 ON BioDataValues(BioDataCube_DataExternal) TABLESPACE INDEXES;

CREATE INDEX DataExternal1 ON DataExternal(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX DataExternal2 ON DataExternal(DataFormat) TABLESPACE INDEXES;
CREATE INDEX DataExternal3 ON DataExternal(DataFormatInfoURI) TABLESPACE INDEXES;
CREATE INDEX DataExternal4 ON DataExternal(FilenameURI) TABLESPACE INDEXES;

CREATE INDEX DataInternal1 ON DataInternal(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX Datum1 ON Datum(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Datum2 ON Datum(Value) TABLESPACE INDEXES;

CREATE INDEX DesignElementDimension1 ON DesignElementDimension(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX DesignElementDimension2 ON DesignElementDimension(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX DesignElementDimension3 ON DesignElementDimension(Identifier) TABLESPACE INDEXES;
CREATE INDEX DesignElementDimension4 ON DesignElementDimension(Name) TABLESPACE INDEXES;

CREATE INDEX DesignElementMapping1 ON DesignElementMapping(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX DesignElementTuple1 ON DesignElementTuple(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX DesignElementTuple2 ON DesignElementTuple(BioAssayTuple) TABLESPACE INDEXES;
CREATE INDEX DesignElementTuple3 ON DesignElementTuple(DesignElement) TABLESPACE INDEXES;

CREATE INDEX QuantitationTypeDimension1 ON QuantitationTypeDimension(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX QuantitationTypeDimension2 ON QuantitationTypeDimension(Identifier) TABLESPACE INDEXES;
CREATE INDEX QuantitationTypeDimension3 ON QuantitationTypeDimension(Name) TABLESPACE INDEXES;

CREATE INDEX QuantitationTypeMapping1 ON QuantitationTypeMapping(DataSetWID) TABLESPACE INDEXES;

CREATE INDEX QuantitationTypeTuple1 ON QuantitationTypeTuple(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX QuantitationTypeTuple2 ON QuantitationTypeTuple(DesignElementTuple) TABLESPACE INDEXES;
CREATE INDEX QuantitationTypeTuple3 ON QuantitationTypeTuple(QuantitationType) TABLESPACE INDEXES;
CREATE INDEX QuantitationTypeTuple4 ON QuantitationTypeTuple(QuantitationTypeTuple_Datum) TABLESPACE INDEXES;

CREATE INDEX BioMaterialMeasurement1 ON BioMaterialMeasurement(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioMaterialMeasurement2 ON BioMaterialMeasurement(BioMaterial) TABLESPACE INDEXES;
CREATE INDEX BioMaterialMeasurement3 ON BioMaterialMeasurement(Measurement) TABLESPACE INDEXES;
CREATE INDEX BioMaterialMeasurement4 ON BioMaterialMeasurement(Treatment) TABLESPACE INDEXES;
CREATE INDEX BioMaterialMeasurement5 ON BioMaterialMeasurement(BioAssayCreation) TABLESPACE INDEXES;

CREATE INDEX CompoundMeasurement1 ON CompoundMeasurement(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX CompoundMeasurement2 ON CompoundMeasurement(Compound_ComponentCompounds) TABLESPACE INDEXES;
CREATE INDEX CompoundMeasurement3 ON CompoundMeasurement(Compound) TABLESPACE INDEXES;
CREATE INDEX CompoundMeasurement4 ON CompoundMeasurement(Measurement) TABLESPACE INDEXES;
CREATE INDEX CompoundMeasurement5 ON CompoundMeasurement(Treatment_CompoundMeasurements) TABLESPACE INDEXES;

CREATE INDEX BioAssay1 ON BioAssay(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioAssay2 ON BioAssay(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX BioAssay3 ON BioAssay(Identifier) TABLESPACE INDEXES;
CREATE INDEX BioAssay4 ON BioAssay(Name) TABLESPACE INDEXES;
CREATE INDEX BioAssay5 ON BioAssay(DerivedBioAssay_Type) TABLESPACE INDEXES;
CREATE INDEX BioAssay6 ON BioAssay(FeatureExtraction) TABLESPACE INDEXES;
CREATE INDEX BioAssay7 ON BioAssay(BioAssayCreation) TABLESPACE INDEXES;

CREATE INDEX Channel1 ON Channel(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Channel2 ON Channel(Identifier) TABLESPACE INDEXES;
CREATE INDEX Channel3 ON Channel(Name) TABLESPACE INDEXES;

CREATE INDEX Image1 ON Image(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Image2 ON Image(Identifier) TABLESPACE INDEXES;
CREATE INDEX Image3 ON Image(Name) TABLESPACE INDEXES;
CREATE INDEX Image4 ON Image(URI) TABLESPACE INDEXES;
CREATE INDEX Image5 ON Image(Image_Format) TABLESPACE INDEXES;
CREATE INDEX Image6 ON Image(PhysicalBioAssay) TABLESPACE INDEXES;

CREATE INDEX BioAssayDataCluster1 ON BioAssayDataCluster(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayDataCluster2 ON BioAssayDataCluster(Identifier) TABLESPACE INDEXES;
CREATE INDEX BioAssayDataCluster3 ON BioAssayDataCluster(Name) TABLESPACE INDEXES;
CREATE INDEX BioAssayDataCluster4 ON BioAssayDataCluster(ClusterBioAssayData) TABLESPACE INDEXES;

CREATE INDEX Node1 ON Node(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Node2 ON Node(BioAssayDataCluster_Nodes) TABLESPACE INDEXES;
CREATE INDEX Node3 ON Node(Node_Nodes) TABLESPACE INDEXES;

CREATE INDEX NodeContents1 ON NodeContents(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX NodeContents2 ON NodeContents(Node_NodeContents) TABLESPACE INDEXES;
CREATE INDEX NodeContents3 ON NodeContents(BioAssayDimension) TABLESPACE INDEXES;
CREATE INDEX NodeContents4 ON NodeContents(DesignElementDimension) TABLESPACE INDEXES;
CREATE INDEX NodeContents5 ON NodeContents(QuantitationDimension) TABLESPACE INDEXES;

CREATE INDEX NodeValue1 ON NodeValue(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX NodeValue2 ON NodeValue(Node_NodeValue) TABLESPACE INDEXES;
CREATE INDEX NodeValue3 ON NodeValue(Name) TABLESPACE INDEXES;
CREATE INDEX NodeValue4 ON NodeValue(Value) TABLESPACE INDEXES;
CREATE INDEX NodeValue5 ON NodeValue(NodeValue_Type) TABLESPACE INDEXES;
CREATE INDEX NodeValue6 ON NodeValue(NodeValue_Scale) TABLESPACE INDEXES;
CREATE INDEX NodeValue7 ON NodeValue(NodeValue_DataType) TABLESPACE INDEXES;

CREATE INDEX Measurement1 ON Measurement(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Measurement2 ON Measurement(Type_) TABLESPACE INDEXES;
CREATE INDEX Measurement3 ON Measurement(Value) TABLESPACE INDEXES;
CREATE INDEX Measurement4 ON Measurement(KindCV) TABLESPACE INDEXES;
CREATE INDEX Measurement5 ON Measurement(OtherKind) TABLESPACE INDEXES;
CREATE INDEX Measurement6 ON Measurement(Measurement_Unit) TABLESPACE INDEXES;

CREATE INDEX Unit1 ON Unit(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Unit2 ON Unit(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX Unit3 ON Unit(UnitName) TABLESPACE INDEXES;
CREATE INDEX Unit4 ON Unit(UnitNameCV) TABLESPACE INDEXES;
CREATE INDEX Unit5 ON Unit(UnitNameCV2) TABLESPACE INDEXES;
CREATE INDEX Unit6 ON Unit(UnitNameCV3) TABLESPACE INDEXES;
CREATE INDEX Unit7 ON Unit(UnitNameCV4) TABLESPACE INDEXES;
CREATE INDEX Unit8 ON Unit(UnitNameCV5) TABLESPACE INDEXES;
CREATE INDEX Unit9 ON Unit(UnitNameCV6) TABLESPACE INDEXES;
CREATE INDEX Unit10 ON Unit(UnitNameCV7) TABLESPACE INDEXES;

CREATE INDEX Parameter1 ON Parameter(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Parameter2 ON Parameter(Identifier) TABLESPACE INDEXES;
CREATE INDEX Parameter3 ON Parameter(Name) TABLESPACE INDEXES;
CREATE INDEX Parameter4 ON Parameter(Parameter_DefaultValue) TABLESPACE INDEXES;
CREATE INDEX Parameter5 ON Parameter(Parameter_DataType) TABLESPACE INDEXES;
CREATE INDEX Parameter6 ON Parameter(Parameterizable_ParameterTypes) TABLESPACE INDEXES;

CREATE INDEX ParameterValue1 ON ParameterValue(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ParameterValue2 ON ParameterValue(Value) TABLESPACE INDEXES;
CREATE INDEX ParameterValue3 ON ParameterValue(ParameterType) TABLESPACE INDEXES;
CREATE INDEX ParameterValue4 ON ParameterValue(ParameterizableApplication) TABLESPACE INDEXES;

CREATE INDEX Parameterizable1 ON Parameterizable(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX Parameterizable2 ON Parameterizable(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX Parameterizable3 ON Parameterizable(Identifier) TABLESPACE INDEXES;
CREATE INDEX Parameterizable4 ON Parameterizable(Name) TABLESPACE INDEXES;
CREATE INDEX Parameterizable5 ON Parameterizable(URI) TABLESPACE INDEXES;
CREATE INDEX Parameterizable6 ON Parameterizable(Model) TABLESPACE INDEXES;
CREATE INDEX Parameterizable7 ON Parameterizable(Make) TABLESPACE INDEXES;
CREATE INDEX Parameterizable8 ON Parameterizable(Hardware_Type) TABLESPACE INDEXES;
CREATE INDEX Parameterizable9 ON Parameterizable(Text) TABLESPACE INDEXES;
CREATE INDEX Parameterizable10 ON Parameterizable(Title) TABLESPACE INDEXES;
CREATE INDEX Parameterizable11 ON Parameterizable(Protocol_Type) TABLESPACE INDEXES;
CREATE INDEX Parameterizable12 ON Parameterizable(Software_Type) TABLESPACE INDEXES;
CREATE INDEX Parameterizable13 ON Parameterizable(Hardware) TABLESPACE INDEXES;

CREATE INDEX ParameterizableApplication1 ON ParameterizableApplication(DataSetWID) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication2 ON ParameterizableApplication(MAGEClass) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication3 ON ParameterizableApplication(ArrayDesign) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication4 ON ParameterizableApplication(ArrayManufacture) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication5 ON ParameterizableApplication(BioEvent_ProtocolApplications) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication6 ON ParameterizableApplication(SerialNumber) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication7 ON ParameterizableApplication(Hardware) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication8 ON ParameterizableApplication(ActivityDate) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication9 ON ParameterizableApplication(ProtocolApplication) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication10 ON ParameterizableApplication(ProtocolApplication2) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication11 ON ParameterizableApplication(Protocol) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication12 ON ParameterizableApplication(Version) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication13 ON ParameterizableApplication(ReleaseDate) TABLESPACE INDEXES;
CREATE INDEX ParameterizableApplication14 ON ParameterizableApplication(Software) TABLESPACE INDEXES;

CREATE INDEX ArrayDesignWIDReporterGrou1 ON ArrayDesignWIDReporterGroupWID(ArrayDesignWID) TABLESPACE INDEXES;
CREATE INDEX ArrayDesignWIDReporterGrou2 ON ArrayDesignWIDReporterGroupWID(ReporterGroupWID) TABLESPACE INDEXES;

CREATE INDEX ArrayDesignWIDCompositeGr1 ON ArrayDesignWIDCompositeGrpWID(ArrayDesignWID) TABLESPACE INDEXES;
CREATE INDEX ArrayDesignWIDCompositeGr2 ON ArrayDesignWIDCompositeGrpWID(CompositeGroupWID) TABLESPACE INDEXES;

CREATE INDEX ArrayDesignWIDContactWID1 ON ArrayDesignWIDContactWID(ArrayDesignWID) TABLESPACE INDEXES;
CREATE INDEX ArrayDesignWIDContactWID2 ON ArrayDesignWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX ComposGrpWIDComposSequenc1 ON ComposGrpWIDComposSequenceWID(CompositeGroupWID) TABLESPACE INDEXES;
CREATE INDEX ComposGrpWIDComposSequenc2 ON ComposGrpWIDComposSequenceWID(CompositeSequenceWID) TABLESPACE INDEXES;

CREATE INDEX ReporterGroupWIDReporte1 ON ReporterGroupWIDReporterWID(ReporterGroupWID) TABLESPACE INDEXES;
CREATE INDEX ReporterGroupWIDReporte2 ON ReporterGroupWIDReporterWID(ReporterWID) TABLESPACE INDEXES;

CREATE INDEX ExperimentWIDContactWID1 ON ExperimentWIDContactWID(ExperimentWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentWIDContactWID2 ON ExperimentWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX ExperimWIDBioAssayDataClus1 ON ExperimWIDBioAssayDataClustWID(ExperimentWID) TABLESPACE INDEXES;
CREATE INDEX ExperimWIDBioAssayDataClus2 ON ExperimWIDBioAssayDataClustWID(BioAssayDataClusterWID) TABLESPACE INDEXES;

CREATE INDEX ExperimentWIDBioAssayDat1 ON ExperimentWIDBioAssayDataWID(ExperimentWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentWIDBioAssayDat2 ON ExperimentWIDBioAssayDataWID(BioAssayDataWID) TABLESPACE INDEXES;

CREATE INDEX ExperimentWIDBioAssayWID1 ON ExperimentWIDBioAssayWID(ExperimentWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentWIDBioAssayWID2 ON ExperimentWIDBioAssayWID(BioAssayWID) TABLESPACE INDEXES;

CREATE INDEX ExperimentDesignWIDBioAssa1 ON ExperimentDesignWIDBioAssayWID(ExperimentDesignWID) TABLESPACE INDEXES;
CREATE INDEX ExperimentDesignWIDBioAssa2 ON ExperimentDesignWIDBioAssayWID(BioAssayWID) TABLESPACE INDEXES;

CREATE INDEX QuantTypeWIDConfidenceIn1 ON QuantTypeWIDConfidenceIndWID(QuantitationTypeWID) TABLESPACE INDEXES;
CREATE INDEX QuantTypeWIDConfidenceIn2 ON QuantTypeWIDConfidenceIndWID(ConfidenceIndicatorWID) TABLESPACE INDEXES;

CREATE INDEX QuantTypeWIDQuantTypeMa1 ON QuantTypeWIDQuantTypeMapWID(QuantitationTypeWID) TABLESPACE INDEXES;
CREATE INDEX QuantTypeWIDQuantTypeMa2 ON QuantTypeWIDQuantTypeMapWID(QuantitationTypeMapWID) TABLESPACE INDEXES;

CREATE INDEX DatabaseWIDContactWID1 ON DatabaseWIDContactWID(DatabaseWID) TABLESPACE INDEXES;
CREATE INDEX DatabaseWIDContactWID2 ON DatabaseWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX ArrayGroupWIDArrayWID1 ON ArrayGroupWIDArrayWID(ArrayGroupWID) TABLESPACE INDEXES;
CREATE INDEX ArrayGroupWIDArrayWID2 ON ArrayGroupWIDArrayWID(ArrayWID) TABLESPACE INDEXES;

CREATE INDEX ArrayManufactureWIDArra1 ON ArrayManufactureWIDArrayWID(ArrayManufactureWID) TABLESPACE INDEXES;
CREATE INDEX ArrayManufactureWIDArra2 ON ArrayManufactureWIDArrayWID(ArrayWID) TABLESPACE INDEXES;

CREATE INDEX ArrayManufactureWIDContac1 ON ArrayManufactureWIDContactWID(ArrayManufactureWID) TABLESPACE INDEXES;
CREATE INDEX ArrayManufactureWIDContac2 ON ArrayManufactureWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX CompositeSeqWIDBioSeqWID1 ON CompositeSeqWIDBioSeqWID(CompositeSequenceWID) TABLESPACE INDEXES;
CREATE INDEX CompositeSeqWIDBioSeqWID2 ON CompositeSeqWIDBioSeqWID(BioSequenceWID) TABLESPACE INDEXES;

CREATE INDEX ComposSeqWIDRepoComposMa1 ON ComposSeqWIDRepoComposMapWID(CompositeSequenceWID) TABLESPACE INDEXES;
CREATE INDEX ComposSeqWIDRepoComposMa2 ON ComposSeqWIDRepoComposMapWID(ReporterCompositeMapWID) TABLESPACE INDEXES;

CREATE INDEX ComposSeqWIDComposComposMa1 ON ComposSeqWIDComposComposMapWID(CompositeSequenceWID) TABLESPACE INDEXES;
CREATE INDEX ComposSeqWIDComposComposMa2 ON ComposSeqWIDComposComposMapWID(CompositeCompositeMapWID) TABLESPACE INDEXES;

CREATE INDEX FeatureWIDFeatureWID1 ON FeatureWIDFeatureWID(FeatureWID1) TABLESPACE INDEXES;
CREATE INDEX FeatureWIDFeatureWID2 ON FeatureWIDFeatureWID(FeatureWID2) TABLESPACE INDEXES;

CREATE INDEX FeatureWIDFeatureWID21 ON FeatureWIDFeatureWID2(FeatureWID1) TABLESPACE INDEXES;
CREATE INDEX FeatureWIDFeatureWID22 ON FeatureWIDFeatureWID2(FeatureWID2) TABLESPACE INDEXES;

CREATE INDEX ReporterWIDBioSequenceWID1 ON ReporterWIDBioSequenceWID(ReporterWID) TABLESPACE INDEXES;
CREATE INDEX ReporterWIDBioSequenceWID2 ON ReporterWIDBioSequenceWID(BioSequenceWID) TABLESPACE INDEXES;

CREATE INDEX ReporterWIDFeatureReporMa1 ON ReporterWIDFeatureReporMapWID(ReporterWID) TABLESPACE INDEXES;
CREATE INDEX ReporterWIDFeatureReporMa2 ON ReporterWIDFeatureReporMapWID(FeatureReporterMapWID) TABLESPACE INDEXES;

CREATE INDEX BioAssayDimensioWIDBioAssa1 ON BioAssayDimensioWIDBioAssayWID(BioAssayDimensionWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayDimensioWIDBioAssa2 ON BioAssayDimensioWIDBioAssayWID(BioAssayWID) TABLESPACE INDEXES;

CREATE INDEX BioAssayMapWIDBioAssayWID1 ON BioAssayMapWIDBioAssayWID(BioAssayMapWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayMapWIDBioAssayWID2 ON BioAssayMapWIDBioAssayWID(BioAssayWID) TABLESPACE INDEXES;

CREATE INDEX BAssayMappingWIDBAssayMa1 ON BAssayMappingWIDBAssayMapWID(BioAssayMappingWID) TABLESPACE INDEXES;
CREATE INDEX BAssayMappingWIDBAssayMa2 ON BAssayMappingWIDBAssayMapWID(BioAssayMapWID) TABLESPACE INDEXES;

CREATE INDEX ComposSeqDimensWIDComposSe1 ON ComposSeqDimensWIDComposSeqWID(CompositeSequenceDimensionWID) TABLESPACE INDEXES;
CREATE INDEX ComposSeqDimensWIDComposSe2 ON ComposSeqDimensWIDComposSeqWID(CompositeSequenceWID) TABLESPACE INDEXES;

CREATE INDEX DesnElMappingWIDDesnElMa1 ON DesnElMappingWIDDesnElMapWID(DesignElementMappingWID) TABLESPACE INDEXES;
CREATE INDEX DesnElMappingWIDDesnElMa2 ON DesnElMappingWIDDesnElMapWID(DesignElementMapWID) TABLESPACE INDEXES;

CREATE INDEX FeatureDimensionWIDFeatur1 ON FeatureDimensionWIDFeatureWID(FeatureDimensionWID) TABLESPACE INDEXES;
CREATE INDEX FeatureDimensionWIDFeatur2 ON FeatureDimensionWIDFeatureWID(FeatureWID) TABLESPACE INDEXES;

CREATE INDEX QuantTypeDimensWIDQuantTyp1 ON QuantTypeDimensWIDQuantTypeWID(QuantitationTypeDimensionWID) TABLESPACE INDEXES;
CREATE INDEX QuantTypeDimensWIDQuantTyp2 ON QuantTypeDimensWIDQuantTypeWID(QuantitationTypeWID) TABLESPACE INDEXES;

CREATE INDEX QuantTypeMapWIDQuantTyp1 ON QuantTypeMapWIDQuantTypeWID(QuantitationTypeMapWID) TABLESPACE INDEXES;
CREATE INDEX QuantTypeMapWIDQuantTyp2 ON QuantTypeMapWIDQuantTypeWID(QuantitationTypeWID) TABLESPACE INDEXES;

CREATE INDEX QuantTyMapWIDQuantTyMapWI1 ON QuantTyMapWIDQuantTyMapWI(QuantitationTypeMappingWID) TABLESPACE INDEXES;
CREATE INDEX QuantTyMapWIDQuantTyMapWI2 ON QuantTyMapWIDQuantTyMapWI(QuantitationTypeMapWID) TABLESPACE INDEXES;

CREATE INDEX ReporterDimensWIDReporte1 ON ReporterDimensWIDReporterWID(ReporterDimensionWID) TABLESPACE INDEXES;
CREATE INDEX ReporterDimensWIDReporte2 ON ReporterDimensWIDReporterWID(ReporterWID) TABLESPACE INDEXES;

CREATE INDEX TransformWIDBioAssayDat1 ON TransformWIDBioAssayDataWID(TransformationWID) TABLESPACE INDEXES;
CREATE INDEX TransformWIDBioAssayDat2 ON TransformWIDBioAssayDataWID(BioAssayDataWID) TABLESPACE INDEXES;

CREATE INDEX BioSourceWIDContactWID1 ON BioSourceWIDContactWID(BioSourceWID) TABLESPACE INDEXES;
CREATE INDEX BioSourceWIDContactWID2 ON BioSourceWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX LabeledExtractWIDCompoun1 ON LabeledExtractWIDCompoundWID(LabeledExtractWID) TABLESPACE INDEXES;
CREATE INDEX LabeledExtractWIDCompoun2 ON LabeledExtractWIDCompoundWID(CompoundWID) TABLESPACE INDEXES;

CREATE INDEX BioAssayWIDChannelWID1 ON BioAssayWIDChannelWID(BioAssayWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayWIDChannelWID2 ON BioAssayWIDChannelWID(ChannelWID) TABLESPACE INDEXES;

CREATE INDEX BioAssayWIDFactorValueWID1 ON BioAssayWIDFactorValueWID(BioAssayWID) TABLESPACE INDEXES;
CREATE INDEX BioAssayWIDFactorValueWID2 ON BioAssayWIDFactorValueWID(FactorValueWID) TABLESPACE INDEXES;

CREATE INDEX ChannelWIDCompoundWID1 ON ChannelWIDCompoundWID(ChannelWID) TABLESPACE INDEXES;
CREATE INDEX ChannelWIDCompoundWID2 ON ChannelWIDCompoundWID(CompoundWID) TABLESPACE INDEXES;

CREATE INDEX DerivBioAWIDDerivBioADat1 ON DerivBioAWIDDerivBioADataWID(DerivedBioAssayWID) TABLESPACE INDEXES;
CREATE INDEX DerivBioAWIDDerivBioADat2 ON DerivBioAWIDDerivBioADataWID(DerivedBioAssayDataWID) TABLESPACE INDEXES;

CREATE INDEX DerivBioAssayWIDBioAssayMa1 ON DerivBioAssayWIDBioAssayMapWID(DerivedBioAssayWID) TABLESPACE INDEXES;
CREATE INDEX DerivBioAssayWIDBioAssayMa2 ON DerivBioAssayWIDBioAssayMapWID(BioAssayMapWID) TABLESPACE INDEXES;

CREATE INDEX ImageWIDChannelWID1 ON ImageWIDChannelWID(ImageWID) TABLESPACE INDEXES;
CREATE INDEX ImageWIDChannelWID2 ON ImageWIDChannelWID(ChannelWID) TABLESPACE INDEXES;

CREATE INDEX ImageAcquisitionWIDImag1 ON ImageAcquisitionWIDImageWID(ImageAcquisitionWID) TABLESPACE INDEXES;
CREATE INDEX ImageAcquisitionWIDImag2 ON ImageAcquisitionWIDImageWID(ImageWID) TABLESPACE INDEXES;

CREATE INDEX MeasBAssayWIDMeasBAssayDat1 ON MeasBAssayWIDMeasBAssayDataWID(MeasuredBioAssayWID) TABLESPACE INDEXES;
CREATE INDEX MeasBAssayWIDMeasBAssayDat2 ON MeasBAssayWIDMeasBAssayDataWID(MeasuredBioAssayDataWID) TABLESPACE INDEXES;

CREATE INDEX HardwareWIDSoftwareWID1 ON HardwareWIDSoftwareWID(HardwareWID) TABLESPACE INDEXES;
CREATE INDEX HardwareWIDSoftwareWID2 ON HardwareWIDSoftwareWID(SoftwareWID) TABLESPACE INDEXES;

CREATE INDEX HardwareWIDContactWID1 ON HardwareWIDContactWID(HardwareWID) TABLESPACE INDEXES;
CREATE INDEX HardwareWIDContactWID2 ON HardwareWIDContactWID(ContactWID) TABLESPACE INDEXES;

CREATE INDEX ProtocolWIDHardwareWID1 ON ProtocolWIDHardwareWID(ProtocolWID) TABLESPACE INDEXES;
CREATE INDEX ProtocolWIDHardwareWID2 ON ProtocolWIDHardwareWID(HardwareWID) TABLESPACE INDEXES;

CREATE INDEX ProtocolWIDSoftwareWID1 ON ProtocolWIDSoftwareWID(ProtocolWID) TABLESPACE INDEXES;
CREATE INDEX ProtocolWIDSoftwareWID2 ON ProtocolWIDSoftwareWID(SoftwareWID) TABLESPACE INDEXES;

CREATE INDEX ProtocolApplWIDPersonWID1 ON ProtocolApplWIDPersonWID(ProtocolApplicationWID) TABLESPACE INDEXES;
CREATE INDEX ProtocolApplWIDPersonWID2 ON ProtocolApplWIDPersonWID(PersonWID) TABLESPACE INDEXES;

CREATE INDEX SoftwareWIDSoftwareWID1 ON SoftwareWIDSoftwareWID(SoftwareWID1) TABLESPACE INDEXES;
CREATE INDEX SoftwareWIDSoftwareWID2 ON SoftwareWIDSoftwareWID(SoftwareWID2) TABLESPACE INDEXES;

CREATE INDEX SoftwareWIDContactWID1 ON SoftwareWIDContactWID(SoftwareWID) TABLESPACE INDEXES;
CREATE INDEX SoftwareWIDContactWID2 ON SoftwareWIDContactWID(ContactWID) TABLESPACE INDEXES;


commit;
