alter table Entry drop constraint FK_Entry;
alter table GeneExpressionData drop constraint FK_GEDBAV;
alter table Valence drop constraint FK_Valence;
alter table LightSource drop constraint FK_LightSource1;
alter table FlowCytometrySample drop constraint FK_FlowCytometrySample1;
alter table FlowCytometrySample drop constraint FK_FlowCytometrySample2;
alter table FlowCytometrySample drop constraint FK_FlowCytometrySample3;
alter table FlowCytometrySample drop constraint FK_FlowCytometrySample4;
alter table FlowCytometrySample drop constraint FK_FlowCytometrySampleDS;
alter table FlowCytometryProbe drop constraint FK_Probe1;
alter table Chemical drop constraint FK_Chemical1;
alter table Reaction drop constraint FK_Reaction;
alter table Interaction drop constraint FK_Interaction1;
alter table Protein drop constraint FK_Protein;
alter table Feature drop constraint FK_Feature;
alter table Function drop constraint FK_Function;
alter table EnzymaticReaction drop constraint FK_EnzymaticReaction1;
alter table EnzymaticReaction drop constraint FK_EnzymaticReaction2;
alter table EnzymaticReaction drop constraint FK_EnzymaticReaction3;
alter table EnzymaticReaction drop constraint FK_EnzymaticReaction4;
alter table GeneticCode drop constraint FK_GeneticCode;
alter table Division drop constraint FK_Division;
alter table Taxon drop constraint FK_Taxon_Division;
alter table Taxon drop constraint FK_Taxon_GeneticCode;
alter table Taxon drop constraint FK_Taxon;
alter table BioSource drop constraint FK_BioSource1;
alter table BioSource drop constraint FK_BioSource2;
alter table BioSubtype drop constraint FK_BioSubtype2;
alter table NucleicAcid drop constraint FK_NucleicAcid1;
alter table NucleicAcid drop constraint FK_NucleicAcid2;
alter table NucleicAcid drop constraint FK_NucleicAcid3;
alter table Subsequence drop constraint FK_Subsequence1;
alter table Subsequence drop constraint FK_Subsequence2;
alter table Gene drop constraint FK_Gene1;
alter table Gene drop constraint FK_Gene2;
alter table Pathway drop constraint FK_Pathway1;
alter table Pathway drop constraint FK_Pathway2;
alter table Computation drop constraint FK_Computation;
alter table Citation drop constraint FK_Citation;
alter table Experiment drop constraint FK_Experiment3;
alter table Experiment drop constraint FK_Experiment4;
alter table Experiment drop constraint FK_Experiment2;
alter table Experiment drop constraint FK_Experiment5;
alter table Experiment drop constraint FK_Experiment6;
alter table ExperimentData drop constraint FK_ExpData1;
alter table ExperimentData drop constraint FK_ExpDataMD;
alter table ExperimentData drop constraint FK_ExpData2;
alter table ChemicalAtom drop constraint FK_ChemicalAtom;
alter table ChemicalBond drop constraint FK_ChemicalBond;
alter table EnzReactionCofactor drop constraint FK_EnzReactionCofactor1;
alter table EnzReactionCofactor drop constraint FK_EnzReactionCofactor2;
alter table EnzReactionAltCompound drop constraint FK_ERAC1;
alter table EnzReactionAltCompound drop constraint FK_ERAC2;
alter table EnzReactionAltCompound drop constraint FK_ERAC3;
alter table EnzReactionInhibitorActivator drop constraint FK_EnzReactionIA1;
alter table Location drop constraint FK_Location;
alter table PathwayLink drop constraint FK_PathwayLink1;
alter table PathwayLink drop constraint FK_PathwayLink2;
alter table PathwayLink drop constraint FK_PathwayLink3;
alter table PathwayReaction drop constraint FK_PathwayReaction1;
alter table PathwayReaction drop constraint FK_PathwayReaction3;
alter table Product drop constraint FK_Product;
alter table Reactant drop constraint FK_Reactant;
alter table InteractionParticipant drop constraint FK_InteractionParticipant1;
alter table SequenceMatch drop constraint FK_SequenceMatch;
alter table Subunit drop constraint FK_Subunit1;
alter table Subunit drop constraint FK_Subunit2;
alter table SuperPathway drop constraint FK_SuperPathway1;
alter table SuperPathway drop constraint FK_SuperPathway2;
alter table TermRelationship drop constraint FK_TermRelationship1;
alter table TermRelationship drop constraint FK_TermRelationship2;
alter table RelatedTerm drop constraint FK_RelatedTerm1;
alter table CitationWIDOtherWID drop constraint FK_CitationWIDOtherWID;
alter table BioSourceWIDBioSubtypeWID drop constraint FK_BioSourceWIDBioSubtypeWID1;
alter table BioSourceWIDBioSubtypeWID drop constraint FK_BioSourceWIDBioSubtypeWID2;
alter table BioSourceWIDGeneWID drop constraint FK_BioSourceWIDGeneWID1;
alter table BioSourceWIDGeneWID drop constraint FK_BioSourceWIDGeneWID2;
alter table BioSourceWIDProteinWID drop constraint FK_BioSourceWIDProteinWID1;
alter table BioSourceWIDProteinWID drop constraint FK_BioSourceWIDProteinWID2;
alter table GeneWIDNucleicAcidWID drop constraint FK_GeneWIDNucleicAcidWID1;
alter table GeneWIDNucleicAcidWID drop constraint FK_GeneWIDNucleicAcidWID2;
alter table GeneWIDProteinWID drop constraint FK_GeneWIDProteinWID1;
alter table GeneWIDProteinWID drop constraint FK_GeneWIDProteinWID2;
alter table ProteinWIDFunctionWID drop constraint FK_ProteinWIDFunctionWID2;
alter table ProteinWIDFunctionWID drop constraint FK_ProteinWIDFunctionWID3;
alter table ExperimentRelationship drop constraint FK_ExpRelationship1;
alter table ExperimentRelationship drop constraint FK_ExpRelationship2;
alter table GelLocation drop constraint FK_GelLocSpotWid;
alter table GelLocation drop constraint FK_GelLocExp;
alter table GelLocation drop constraint FK_GelLocDataset;
alter table ProteinWIDSpotWID drop constraint FK_ProteinWIDSpotWID1;
alter table ProteinWIDSpotWID drop constraint FK_ProteinWIDSpotWID2;
alter table Spot drop constraint FK_Spot;
alter table SpotIdMethod drop constraint FK_SpotIdMethDataset;
alter table SpotWIDSpotIdMethodWID drop constraint FK_SpotWIDMethWID1;
alter table SpotWIDSpotIdMethodWID drop constraint FK_SpotWIDMethWID2;
alter table NameValueType drop constraint FK_NameValueType1;
alter table NameValueType drop constraint FK_NameValueType66;
alter table Contact drop constraint FK_Contact1;
alter table Contact drop constraint FK_Contact3;
alter table Contact drop constraint FK_Contact4;
alter table ArrayDesign drop constraint FK_ArrayDesign1;
alter table ArrayDesign drop constraint FK_ArrayDesign3;
alter table DesignElementGroup drop constraint FK_DesignElementGroup1;
alter table DesignElementGroup drop constraint FK_DesignElementGroup3;
alter table DesignElementGroup drop constraint FK_DesignElementGroup4;
alter table DesignElementGroup drop constraint FK_DesignElementGroup5;
alter table DesignElementGroup drop constraint FK_DesignElementGroup6;
alter table DesignElementGroup drop constraint FK_DesignElementGroup7;
alter table Zone drop constraint FK_Zone1;
alter table Zone drop constraint FK_Zone3;
alter table Zone drop constraint FK_Zone4;
alter table ZoneGroup drop constraint FK_ZoneGroup1;
alter table ZoneGroup drop constraint FK_ZoneGroup2;
alter table ZoneGroup drop constraint FK_ZoneGroup3;
alter table ZoneGroup drop constraint FK_ZoneGroup4;
alter table ZoneLayout drop constraint FK_ZoneLayout1;
alter table ZoneLayout drop constraint FK_ZoneLayout2;
alter table ExperimentDesign drop constraint FK_ExperimentDesign1;
alter table ExperimentDesign drop constraint FK_ExperimentDesign3;
alter table ExperimentalFactor drop constraint FK_ExperimentalFactor1;
alter table ExperimentalFactor drop constraint FK_ExperimentalFactor3;
alter table ExperimentalFactor drop constraint FK_ExperimentalFactor4;
alter table FactorValue drop constraint FK_FactorValue1;
alter table FactorValue drop constraint FK_FactorValue3;
alter table FactorValue drop constraint FK_FactorValue4;
alter table FactorValue drop constraint FK_FactorValue5;
alter table FactorValue drop constraint FK_FactorValue6;
alter table QuantitationType drop constraint FK_QuantitationType1;
alter table QuantitationType drop constraint FK_QuantitationType3;
alter table QuantitationType drop constraint FK_QuantitationType4;
alter table QuantitationType drop constraint FK_QuantitationType5;
alter table QuantitationType drop constraint FK_QuantitationType6;
alter table Database_ drop constraint FK_Database_1;
alter table Array_ drop constraint FK_Array_1;
alter table Array_ drop constraint FK_Array_3;
alter table Array_ drop constraint FK_Array_4;
alter table Array_ drop constraint FK_Array_5;
alter table ArrayGroup drop constraint FK_ArrayGroup1;
alter table ArrayGroup drop constraint FK_ArrayGroup3;
alter table ArrayGroup drop constraint FK_ArrayGroup4;
alter table ArrayManufacture drop constraint FK_ArrayManufacture1;
alter table ArrayManufactureDeviation drop constraint FK_ArrayManufactureDeviation1;
alter table ArrayManufactureDeviation drop constraint FK_ArrayManufactureDeviation2;
alter table FeatureDefect drop constraint FK_FeatureDefect1;
alter table FeatureDefect drop constraint FK_FeatureDefect2;
alter table FeatureDefect drop constraint FK_FeatureDefect3;
alter table FeatureDefect drop constraint FK_FeatureDefect4;
alter table FeatureDefect drop constraint FK_FeatureDefect5;
alter table Fiducial drop constraint FK_Fiducial1;
alter table Fiducial drop constraint FK_Fiducial3;
alter table Fiducial drop constraint FK_Fiducial4;
alter table Fiducial drop constraint FK_Fiducial5;
alter table Fiducial drop constraint FK_Fiducial6;
alter table ManufactureLIMS drop constraint FK_ManufactureLIMS1;
alter table ManufactureLIMS drop constraint FK_ManufactureLIMS3;
alter table ManufactureLIMS drop constraint FK_ManufactureLIMS4;
alter table ManufactureLIMS drop constraint FK_ManufactureLIMS5;
alter table PositionDelta drop constraint FK_PositionDelta1;
alter table PositionDelta drop constraint FK_PositionDelta2;
alter table ZoneDefect drop constraint FK_ZoneDefect1;
alter table ZoneDefect drop constraint FK_ZoneDefect2;
alter table ZoneDefect drop constraint FK_ZoneDefect3;
alter table ZoneDefect drop constraint FK_ZoneDefect4;
alter table ZoneDefect drop constraint FK_ZoneDefect5;
alter table SeqFeatureLocation drop constraint FK_SeqFeatureLocation1;
alter table SeqFeatureLocation drop constraint FK_SeqFeatureLocation2;
alter table SeqFeatureLocation drop constraint FK_SeqFeatureLocation3;
alter table SeqFeatureLocation drop constraint FK_SeqFeatureLocation4;
alter table SequencePosition drop constraint FK_SequencePosition1;
alter table SequencePosition drop constraint FK_SequencePosition2;
alter table SequencePosition drop constraint FK_SequencePosition3;
alter table SequencePosition drop constraint FK_SequencePosition4;
alter table SequencePosition drop constraint FK_SequencePosition5;
alter table DesignElement drop constraint FK_DesignElement1;
alter table DesignElement drop constraint FK_DesignElement3;
alter table DesignElement drop constraint FK_DesignElement4;
alter table DesignElement drop constraint FK_DesignElement5;
alter table DesignElement drop constraint FK_DesignElement6;
alter table DesignElement drop constraint FK_DesignElement7;
alter table DesignElement drop constraint FK_DesignElement8;
alter table DesignElement drop constraint FK_DesignElement9;
alter table FeatureInformation drop constraint FK_FeatureInformation1;
alter table FeatureInformation drop constraint FK_FeatureInformation2;
alter table FeatureInformation drop constraint FK_FeatureInformation3;
alter table FeatureLocation drop constraint FK_FeatureLocation1;
alter table MismatchInformation drop constraint FK_MismatchInformation1;
alter table MismatchInformation drop constraint FK_MismatchInformation2;
alter table MismatchInformation drop constraint FK_MismatchInformation3;
alter table MismatchInformation drop constraint FK_MismatchInformation4;
alter table Position_ drop constraint FK_Position_1;
alter table Position_ drop constraint FK_Position_2;
alter table BioEvent drop constraint FK_BioEvent1;
alter table BioEvent drop constraint FK_BioEvent3;
alter table BioEvent drop constraint FK_BioEvent4;
alter table BioEvent drop constraint FK_BioEvent5;
alter table BioEvent drop constraint FK_BioEvent6;
alter table BioEvent drop constraint FK_BioEvent7;
alter table BioEvent drop constraint FK_BioEvent8;
alter table BioEvent drop constraint FK_BioEvent9;
alter table BioEvent drop constraint FK_BioEvent10;
alter table BioEvent drop constraint FK_BioEvent11;
alter table BioEvent drop constraint FK_BioEvent12;
alter table BioEvent drop constraint FK_BioEvent13;
alter table BioEvent drop constraint FK_BioEvent14;
alter table BioEvent drop constraint FK_BioEvent15;
alter table BioEvent drop constraint FK_BioEvent16;
alter table BioEvent drop constraint FK_BioEvent17;
alter table BioEvent drop constraint FK_BioEvent18;
alter table BioEvent drop constraint FK_BioEvent19;
alter table BioEvent drop constraint FK_BioEvent20;
alter table BioEvent drop constraint FK_BioEvent21;
alter table BioAssayData drop constraint FK_BioAssayData1;
alter table BioAssayData drop constraint FK_BioAssayData3;
alter table BioAssayData drop constraint FK_BioAssayData4;
alter table BioAssayData drop constraint FK_BioAssayData5;
alter table BioAssayData drop constraint FK_BioAssayData6;
alter table BioAssayData drop constraint FK_BioAssayData7;
alter table BioAssayDimension drop constraint FK_BioAssayDimension1;
alter table BioAssayMapping drop constraint FK_BioAssayMapping1;
alter table BioAssayTuple drop constraint FK_BioAssayTuple1;
alter table BioAssayTuple drop constraint FK_BioAssayTuple2;
alter table BioAssayTuple drop constraint FK_BioAssayTuple3;
alter table BioDataValues drop constraint FK_BioDataValues1;
alter table BioDataValues drop constraint FK_BioDataValues2;
alter table BioDataValues drop constraint FK_BioDataValues3;
alter table DataExternal drop constraint FK_DataExternal1;
alter table DataInternal drop constraint FK_DataInternal1;
alter table Datum drop constraint FK_Datum1;
alter table DesignElementDimension drop constraint FK_DesignElementDimension1;
alter table DesignElementMapping drop constraint FK_DesignElementMapping1;
alter table DesignElementTuple drop constraint FK_DesignElementTuple1;
alter table DesignElementTuple drop constraint FK_DesignElementTuple2;
alter table DesignElementTuple drop constraint FK_DesignElementTuple3;
alter table QuantitationTypeDimension drop constraint FK_QuantitationTypeDimension1;
alter table QuantitationTypeMapping drop constraint FK_QuantitationTypeMapping1;
alter table QuantitationTypeTuple drop constraint FK_QuantitationTypeTuple1;
alter table QuantitationTypeTuple drop constraint FK_QuantitationTypeTuple2;
alter table QuantitationTypeTuple drop constraint FK_QuantitationTypeTuple3;
alter table QuantitationTypeTuple drop constraint FK_QuantitationTypeTuple4;
alter table BioMaterialMeasurement drop constraint FK_BioMaterialMeasurement1;
alter table BioMaterialMeasurement drop constraint FK_BioMaterialMeasurement2;
alter table BioMaterialMeasurement drop constraint FK_BioMaterialMeasurement3;
alter table BioMaterialMeasurement drop constraint FK_BioMaterialMeasurement4;
alter table BioMaterialMeasurement drop constraint FK_BioMaterialMeasurement5;
alter table CompoundMeasurement drop constraint FK_CompoundMeasurement1;
alter table CompoundMeasurement drop constraint FK_CompoundMeasurement2;
alter table CompoundMeasurement drop constraint FK_CompoundMeasurement3;
alter table CompoundMeasurement drop constraint FK_CompoundMeasurement4;
alter table CompoundMeasurement drop constraint FK_CompoundMeasurement5;
alter table BioAssay drop constraint FK_BioAssay1;
alter table BioAssay drop constraint FK_BioAssay3;
alter table BioAssay drop constraint FK_BioAssay4;
alter table BioAssay drop constraint FK_BioAssay5;
alter table Channel drop constraint FK_Channel1;
alter table Image drop constraint FK_Image1;
alter table Image drop constraint FK_Image3;
alter table Image drop constraint FK_Image4;
alter table BioAssayDataCluster drop constraint FK_BioAssayDataCluster1;
alter table BioAssayDataCluster drop constraint FK_BioAssayDataCluster3;
alter table Node drop constraint FK_Node1;
alter table Node drop constraint FK_Node3;
alter table Node drop constraint FK_Node4;
alter table NodeContents drop constraint FK_NodeContents1;
alter table NodeContents drop constraint FK_NodeContents3;
alter table NodeContents drop constraint FK_NodeContents4;
alter table NodeContents drop constraint FK_NodeContents5;
alter table NodeContents drop constraint FK_NodeContents6;
alter table NodeValue drop constraint FK_NodeValue1;
alter table NodeValue drop constraint FK_NodeValue2;
alter table NodeValue drop constraint FK_NodeValue3;
alter table NodeValue drop constraint FK_NodeValue4;
alter table NodeValue drop constraint FK_NodeValue5;
alter table Measurement drop constraint FK_Measurement1;
alter table Measurement drop constraint FK_Measurement2;
alter table Unit drop constraint FK_Unit1;
alter table Parameter drop constraint FK_Parameter1;
alter table Parameter drop constraint FK_Parameter3;
alter table Parameter drop constraint FK_Parameter4;
alter table Parameter drop constraint FK_Parameter5;
alter table ParameterValue drop constraint FK_ParameterValue1;
alter table ParameterValue drop constraint FK_ParameterValue2;
alter table ParameterValue drop constraint FK_ParameterValue3;
alter table Parameterizable drop constraint FK_Parameterizable1;
alter table Parameterizable drop constraint FK_Parameterizable3;
alter table Parameterizable drop constraint FK_Parameterizable4;
alter table Parameterizable drop constraint FK_Parameterizable5;
alter table Parameterizable drop constraint FK_Parameterizable6;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio1;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio3;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio4;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio5;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio6;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio7;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio8;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio9;
alter table ParameterizableApplication drop constraint FK_ParameterizableApplicatio10;
alter table ArrayDesignWIDReporterGroupWID drop constraint FK_ArrayDesignWIDReporterGro1;
alter table ArrayDesignWIDReporterGroupWID drop constraint FK_ArrayDesignWIDReporterGro2;
alter table ArrayDesignWIDCompositeGrpWID drop constraint FK_ArrayDesignWIDCompositeGr1;
alter table ArrayDesignWIDCompositeGrpWID drop constraint FK_ArrayDesignWIDCompositeGr2;
alter table ArrayDesignWIDContactWID drop constraint FK_ArrayDesignWIDContactWID1;
alter table ArrayDesignWIDContactWID drop constraint FK_ArrayDesignWIDContactWID2;
alter table ComposGrpWIDComposSequenceWID drop constraint FK_ComposGrpWIDComposSequenc1;
alter table ComposGrpWIDComposSequenceWID drop constraint FK_ComposGrpWIDComposSequenc2;
alter table ReporterGroupWIDReporterWID drop constraint FK_ReporterGroupWIDReporterW1;
alter table ReporterGroupWIDReporterWID drop constraint FK_ReporterGroupWIDReporterW2;
alter table ExperimentWIDContactWID drop constraint FK_ExperimentWIDContactWID1;
alter table ExperimentWIDContactWID drop constraint FK_ExperimentWIDContactWID2;
alter table ExperimWIDBioAssayDataClustWID drop constraint FK_ExperimWIDBioAssayDataClu1;
alter table ExperimWIDBioAssayDataClustWID drop constraint FK_ExperimWIDBioAssayDataClu2;
alter table ExperimentWIDBioAssayDataWID drop constraint FK_ExperimentWIDBioAssayData1;
alter table ExperimentWIDBioAssayDataWID drop constraint FK_ExperimentWIDBioAssayData2;
alter table ExperimentWIDBioAssayWID drop constraint FK_ExperimentWIDBioAssayWID1;
alter table ExperimentWIDBioAssayWID drop constraint FK_ExperimentWIDBioAssayWID2;
alter table ExperimentDesignWIDBioAssayWID drop constraint FK_ExperimentDesignWIDBioAss1;
alter table ExperimentDesignWIDBioAssayWID drop constraint FK_ExperimentDesignWIDBioAss2;
alter table QuantTypeWIDConfidenceIndWID drop constraint FK_QuantTypeWIDConfidenceInd1;
alter table QuantTypeWIDConfidenceIndWID drop constraint FK_QuantTypeWIDConfidenceInd2;
alter table QuantTypeWIDQuantTypeMapWID drop constraint FK_QuantTypeWIDQuantTypeMapW1;
alter table QuantTypeWIDQuantTypeMapWID drop constraint FK_QuantTypeWIDQuantTypeMapW2;
alter table DatabaseWIDContactWID drop constraint FK_DatabaseWIDContactWID1;
alter table DatabaseWIDContactWID drop constraint FK_DatabaseWIDContactWID2;
alter table ArrayGroupWIDArrayWID drop constraint FK_ArrayGroupWIDArrayWID1;
alter table ArrayGroupWIDArrayWID drop constraint FK_ArrayGroupWIDArrayWID2;
alter table ArrayManufactureWIDArrayWID drop constraint FK_ArrayManufactureWIDArrayW1;
alter table ArrayManufactureWIDArrayWID drop constraint FK_ArrayManufactureWIDArrayW2;
alter table ArrayManufactureWIDContactWID drop constraint FK_ArrayManufactureWIDContac1;
alter table ArrayManufactureWIDContactWID drop constraint FK_ArrayManufactureWIDContac2;
alter table CompositeSeqWIDBioSeqWID drop constraint FK_CompositeSeqWIDBioSeqWID1;
alter table ComposSeqWIDRepoComposMapWID drop constraint FK_ComposSeqWIDRepoComposMap1;
alter table ComposSeqWIDRepoComposMapWID drop constraint FK_ComposSeqWIDRepoComposMap2;
alter table ComposSeqWIDComposComposMapWID drop constraint FK_ComposSeqWIDComposComposM1;
alter table ComposSeqWIDComposComposMapWID drop constraint FK_ComposSeqWIDComposComposM2;
alter table FeatureWIDFeatureWID drop constraint FK_FeatureWIDFeatureWID1;
alter table FeatureWIDFeatureWID drop constraint FK_FeatureWIDFeatureWID2;
alter table FeatureWIDFeatureWID2 drop constraint FK_FeatureWIDFeatureWID21;
alter table FeatureWIDFeatureWID2 drop constraint FK_FeatureWIDFeatureWID22;
alter table ReporterWIDBioSequenceWID drop constraint FK_ReporterWIDBioSequenceWID1;
alter table ReporterWIDFeatureReporMapWID drop constraint FK_ReporterWIDFeatureReporMa1;
alter table ReporterWIDFeatureReporMapWID drop constraint FK_ReporterWIDFeatureReporMa2;
alter table BioAssayDimensioWIDBioAssayWID drop constraint FK_BioAssayDimensioWIDBioAss1;
alter table BioAssayDimensioWIDBioAssayWID drop constraint FK_BioAssayDimensioWIDBioAss2;
alter table BioAssayMapWIDBioAssayWID drop constraint FK_BioAssayMapWIDBioAssayWID1;
alter table BioAssayMapWIDBioAssayWID drop constraint FK_BioAssayMapWIDBioAssayWID2;
alter table BAssayMappingWIDBAssayMapWID drop constraint FK_BAssayMappingWIDBAssayMap1;
alter table BAssayMappingWIDBAssayMapWID drop constraint FK_BAssayMappingWIDBAssayMap2;
alter table ComposSeqDimensWIDComposSeqWID drop constraint FK_ComposSeqDimensWIDComposS1;
alter table ComposSeqDimensWIDComposSeqWID drop constraint FK_ComposSeqDimensWIDComposS2;
alter table DesnElMappingWIDDesnElMapWID drop constraint FK_DesnElMappingWIDDesnElMap1;
alter table DesnElMappingWIDDesnElMapWID drop constraint FK_DesnElMappingWIDDesnElMap2;
alter table FeatureDimensionWIDFeatureWID drop constraint FK_FeatureDimensionWIDFeatur1;
alter table FeatureDimensionWIDFeatureWID drop constraint FK_FeatureDimensionWIDFeatur2;
alter table QuantTypeDimensWIDQuantTypeWID drop constraint FK_QuantTypeDimensWIDQuantTy1;
alter table QuantTypeDimensWIDQuantTypeWID drop constraint FK_QuantTypeDimensWIDQuantTy2;
alter table QuantTypeMapWIDQuantTypeWID drop constraint FK_QuantTypeMapWIDQuantTypeW1;
alter table QuantTypeMapWIDQuantTypeWID drop constraint FK_QuantTypeMapWIDQuantTypeW2;
alter table QuantTyMapWIDQuantTyMapWI drop constraint FK_QuantTyMapWIDQuantTyMapWI1;
alter table QuantTyMapWIDQuantTyMapWI drop constraint FK_QuantTyMapWIDQuantTyMapWI2;
alter table ReporterDimensWIDReporterWID drop constraint FK_ReporterDimensWIDReporter1;
alter table ReporterDimensWIDReporterWID drop constraint FK_ReporterDimensWIDReporter2;
alter table TransformWIDBioAssayDataWID drop constraint FK_TransformWIDBioAssayDataW1;
alter table TransformWIDBioAssayDataWID drop constraint FK_TransformWIDBioAssayDataW2;
alter table BioSourceWIDContactWID drop constraint FK_BioSourceWIDContactWID1;
alter table BioSourceWIDContactWID drop constraint FK_BioSourceWIDContactWID2;
alter table LabeledExtractWIDCompoundWID drop constraint FK_LabeledExtractWIDCompound1;
alter table LabeledExtractWIDCompoundWID drop constraint FK_LabeledExtractWIDCompound2;
alter table BioAssayWIDChannelWID drop constraint FK_BioAssayWIDChannelWID1;
alter table BioAssayWIDChannelWID drop constraint FK_BioAssayWIDChannelWID2;
alter table BioAssayWIDFactorValueWID drop constraint FK_BioAssayWIDFactorValueWID1;
alter table BioAssayWIDFactorValueWID drop constraint FK_BioAssayWIDFactorValueWID2;
alter table ChannelWIDCompoundWID drop constraint FK_ChannelWIDCompoundWID1;
alter table ChannelWIDCompoundWID drop constraint FK_ChannelWIDCompoundWID2;
alter table DerivBioAWIDDerivBioADataWID drop constraint FK_DerivBioAWIDDerivBioAData1;
alter table DerivBioAWIDDerivBioADataWID drop constraint FK_DerivBioAWIDDerivBioAData2;
alter table DerivBioAssayWIDBioAssayMapWID drop constraint FK_DerivBioAssayWIDBioAssayM1;
alter table DerivBioAssayWIDBioAssayMapWID drop constraint FK_DerivBioAssayWIDBioAssayM2;
alter table ImageWIDChannelWID drop constraint FK_ImageWIDChannelWID1;
alter table ImageWIDChannelWID drop constraint FK_ImageWIDChannelWID2;
alter table ImageAcquisitionWIDImageWID drop constraint FK_ImageAcquisitionWIDImageW1;
alter table ImageAcquisitionWIDImageWID drop constraint FK_ImageAcquisitionWIDImageW2;
alter table MeasBAssayWIDMeasBAssayDataWID drop constraint FK_MeasBAssayWIDMeasBAssayDa1;
alter table MeasBAssayWIDMeasBAssayDataWID drop constraint FK_MeasBAssayWIDMeasBAssayDa2;
alter table HardwareWIDSoftwareWID drop constraint FK_HardwareWIDSoftwareWID1;
alter table HardwareWIDSoftwareWID drop constraint FK_HardwareWIDSoftwareWID2;
alter table HardwareWIDContactWID drop constraint FK_HardwareWIDContactWID1;
alter table HardwareWIDContactWID drop constraint FK_HardwareWIDContactWID2;
alter table ProtocolWIDHardwareWID drop constraint FK_ProtocolWIDHardwareWID1;
alter table ProtocolWIDHardwareWID drop constraint FK_ProtocolWIDHardwareWID2;
alter table ProtocolWIDSoftwareWID drop constraint FK_ProtocolWIDSoftwareWID1;
alter table ProtocolWIDSoftwareWID drop constraint FK_ProtocolWIDSoftwareWID2;
alter table ProtocolApplWIDPersonWID drop constraint FK_ProtocolApplWIDPersonWID1;
alter table ProtocolApplWIDPersonWID drop constraint FK_ProtocolApplWIDPersonWID2;
alter table SoftwareWIDSoftwareWID drop constraint FK_SoftwareWIDSoftwareWID1;
alter table SoftwareWIDSoftwareWID drop constraint FK_SoftwareWIDSoftwareWID2;
alter table SoftwareWIDContactWID drop constraint FK_SoftwareWIDContactWID1;
alter table SoftwareWIDContactWID drop constraint FK_SoftwareWIDContactWID2;
drop table Warehouse;
drop table WIDTable;
drop table SpecialWIDTable;
drop table Enumeration;
drop table DataSet;
drop table Entry;
drop table GeneExpressionData;
drop table Element;
drop table Valence;
drop table LightSource;
drop table FlowCytometrySample;
drop table FlowCytometryProbe;
drop table Chemical;
drop table Reaction;
drop table Interaction;
drop table Protein;
drop table Feature;
drop table Function;
drop table EnzymaticReaction;
drop table GeneticCode;
drop table Division;
drop table Taxon;
drop table BioSource;
drop table BioSubtype;
drop table NucleicAcid;
drop table Subsequence;
drop table Gene;
drop table Pathway;
drop table Term;
drop table Computation;
drop table Citation;
drop table Archive;
drop table Experiment;
drop table ExperimentData;
drop table Support;
drop table ChemicalAtom;
drop table ChemicalBond;
drop table EnzReactionCofactor;
drop table EnzReactionAltCompound;
drop table EnzReactionInhibitorActivator;
drop table Location;
drop table PathwayLink;
drop table PathwayReaction;
drop table Product;
drop table Reactant;
drop table InteractionParticipant;
drop table SequenceMatch;
drop table Subunit;
drop table SuperPathway;
drop table TermRelationship;
drop table RelatedTerm;
drop table CitationWIDOtherWID;
drop table CommentTable;
drop table CrossReference;
drop table Description;
drop table DBID;
drop table SynonymTable;
drop table ToolAdvice;
drop table BioSourceWIDBioSubtypeWID;
drop table BioSourceWIDGeneWID;
drop table BioSourceWIDProteinWID;
drop table GeneWIDNucleicAcidWID;
drop table GeneWIDProteinWID;
drop table ProteinWIDFunctionWID;
drop table ExperimentRelationship;
drop table GelLocation;
drop table ProteinWIDSpotWID;
drop table Spot;
drop table SpotIdMethod;
drop table SpotWIDSpotIdMethodWID;
drop table NameValueType;
drop table Contact;
drop table ArrayDesign;
drop table DesignElementGroup;
drop table Zone;
drop table ZoneGroup;
drop table ZoneLayout;
drop table ExperimentDesign;
drop table ExperimentalFactor;
drop table FactorValue;
drop table QuantitationType;
drop table Database_;
drop table Array_;
drop table ArrayGroup;
drop table ArrayManufacture;
drop table ArrayManufactureDeviation;
drop table FeatureDefect;
drop table Fiducial;
drop table ManufactureLIMS;
drop table PositionDelta;
drop table ZoneDefect;
drop table SeqFeatureLocation;
drop table SequencePosition;
drop table DesignElement;
drop table FeatureInformation;
drop table FeatureLocation;
drop table MismatchInformation;
drop table Position_;
drop table BioEvent;
drop table BioAssayData;
drop table BioAssayDimension;
drop table BioAssayMapping;
drop table BioAssayTuple;
drop table BioDataValues;
drop table DataExternal;
drop table DataInternal;
drop table Datum;
drop table DesignElementDimension;
drop table DesignElementMapping;
drop table DesignElementTuple;
drop table QuantitationTypeDimension;
drop table QuantitationTypeMapping;
drop table QuantitationTypeTuple;
drop table BioMaterialMeasurement;
drop table CompoundMeasurement;
drop table BioAssay;
drop table Channel;
drop table Image;
drop table BioAssayDataCluster;
drop table Node;
drop table NodeContents;
drop table NodeValue;
drop table Measurement;
drop table Unit;
drop table Parameter;
drop table ParameterValue;
drop table Parameterizable;
drop table ParameterizableApplication;
drop table ArrayDesignWIDReporterGroupWID;
drop table ArrayDesignWIDCompositeGrpWID;
drop table ArrayDesignWIDContactWID;
drop table ComposGrpWIDComposSequenceWID;
drop table ReporterGroupWIDReporterWID;
drop table ExperimentWIDContactWID;
drop table ExperimWIDBioAssayDataClustWID;
drop table ExperimentWIDBioAssayDataWID;
drop table ExperimentWIDBioAssayWID;
drop table ExperimentDesignWIDBioAssayWID;
drop table QuantTypeWIDConfidenceIndWID;
drop table QuantTypeWIDQuantTypeMapWID;
drop table DatabaseWIDContactWID;
drop table ArrayGroupWIDArrayWID;
drop table ArrayManufactureWIDArrayWID;
drop table ArrayManufactureWIDContactWID;
drop table CompositeSeqWIDBioSeqWID;
drop table ComposSeqWIDRepoComposMapWID;
drop table ComposSeqWIDComposComposMapWID;
drop table FeatureWIDFeatureWID;
drop table FeatureWIDFeatureWID2;
drop table ReporterWIDBioSequenceWID;
drop table ReporterWIDFeatureReporMapWID;
drop table BioAssayDimensioWIDBioAssayWID;
drop table BioAssayMapWIDBioAssayWID;
drop table BAssayMappingWIDBAssayMapWID;
drop table ComposSeqDimensWIDComposSeqWID;
drop table DesnElMappingWIDDesnElMapWID;
drop table FeatureDimensionWIDFeatureWID;
drop table QuantTypeDimensWIDQuantTypeWID;
drop table QuantTypeMapWIDQuantTypeWID;
drop table QuantTyMapWIDQuantTyMapWI;
drop table ReporterDimensWIDReporterWID;
drop table TransformWIDBioAssayDataWID;
drop table BioSourceWIDContactWID;
drop table LabeledExtractWIDCompoundWID;
drop table BioAssayWIDChannelWID;
drop table BioAssayWIDFactorValueWID;
drop table ChannelWIDCompoundWID;
drop table DerivBioAWIDDerivBioADataWID;
drop table DerivBioAssayWIDBioAssayMapWID;
drop table ImageWIDChannelWID;
drop table ImageAcquisitionWIDImageWID;
drop table MeasBAssayWIDMeasBAssayDataWID;
drop table HardwareWIDSoftwareWID;
drop table HardwareWIDContactWID;
drop table ProtocolWIDHardwareWID;
drop table ProtocolWIDSoftwareWID;
drop table ProtocolApplWIDPersonWID;
drop table SoftwareWIDSoftwareWID;
drop table SoftwareWIDContactWID;
drop SEQUENCE WID_sequence;
drop SEQUENCE SpecialWID_sequence;
-- Destroy the capability to flash restore tables, reclaiming space.
-- This only works for Oracle 9+
PURGE RECYCLEBIN;

commit;
