# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-02 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('cyanodesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='sbml',
            field=django_extensions.db.fields.json.JSONField(default=dict, verbose_name='Model as SBML JSON'),
        ),
    ]
